#!/bin/bash --norc

# More safety, by turning some bugs into errors. Without 'errexit' you
# don't need ! and can replace PIPESTATUS with a simple $?, but then
# we would need to remember to explcitly test return status for each
# command. Note that ! hides the exit status of the executed command.
# Due to this we have to use PIPESTATUS to get to it and no history
# expansion when using '!' in for instance echo strings.
set -o errexit -o pipefail -o noclobber -o nounset +o history

# Path to this script
_FRIJA_PROGRAM_PATH=$(readlink -e "${0}")
_BOOTSTRAP_PATH="${_FRIJA_PROGRAM_PATH}"

FENSALIR_USER_CONFIG_PATH=""
# Set $FENSALIR_USER_CONFIG_PATH unless $JENKINS_HOME is set
if [[ ! -v JENKINS_HOME ]]; then

    _unameOut="$(uname -s)"
    if [[ "${_unameOut}" == "SunOS" ]]; then
        cat <<EOF

ERROR: Fensalir non-Jenkins bootstrap process not supported on Solaris.

EOF
        exit 1
    fi

    # Ensure $XDG_CONFIG_HOME is set
    XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
    FENSALIR_USER_CONFIG_PATH="${XDG_CONFIG_HOME}/Fensalir"
fi

# Command line options for this script

# - Option followed by : indicate a required argument to option
# - Option followed by :: indicate an optional argument to option
_FRIJA_SUBCOMMAND_OPTIONS="C:S:D:licWLvhdf:"

# - Option followed by : indicate a required argument to option
# - Option followed by :: indicate an optional argument to option
# - Comma (,) separates multiple long options
_FRIJA_SUBCOMMAND_LONGOPTS="country:,site:,domain:,list,instructions,code,windows,linux,verbose,help,debug,dry-run,force-os:"



# Internal states
DRY_RUN="n"
VERBOSE="n"
DEBUG="n"
osOverride=""
initMessage=""

# Silence warning from shellcheck about $BOLD not being assigned. It
# will be assigned when .core_preamble.bash is sourced below.
BOLD=""

function _frija_subcommand_usage()
{
    cat <<EOF
${BOLD}Usage:${CLEAR} ${_FRIJA_USAGE_NAME} OPTION

  Used for bootstraping installation of the Fensalir; ${BOLD}frija${CLEAR} and ${BOLD}volla${CLEAR}.

  As part of the bootstrapping process you must also set the country,
  site, and development domain you are working in.

  If you are looking for a way to update Fensalir repo, then please use
  frija update command instead.

${BOLD}Options:${CLEAR}
  -CCOUNTRY,          country you are located in as COUNTRY
   --country=COUNTRY
  -SSITE,             site SITE located in COUNTRY you are located at
    --site=SITE
  -DDOMAIN,           development domain DOMAIN (located in COUNTRY and SITE)
    --domain=DOMAIN      you are working in
  -l, --list          override default behavior of setting by instead listing
                        available values;
                          - if no country given, then countries are listed
                          - if only country given, then list sites
                          - if country+site given, then list domains
                          - if country+site+domain given, then verify combo
  -i, --instructions  print instructions for how to enable Fensalir
                        command in current shell as well as in all future
                        sessions
  -c, --code          just show the Frija initialization code for .bash_profile
  -W, --windows       print Windows-specific instructions
  -L, --linux         print Linux-specific instructions
  -v, --verbose       verbose output
  -h, --help          print this message
  --debug             enable debug printouts
                        ${BOLD}Note:${CLEAR} Debug messages are prefixed with
                              "*** LINE  " where LINE is current line
                              number and written to stderr.
  -d, --dry-run       just echo command lines instead of executing them
  -fOS, --force=OS    force command to assume given OS instead of detected OS

${BOLD}Examples:${CLEAR}
  ${BOLD}$ bootstrap --country=SE --site=TN --domain=Gride-H/S${CLEAR}

  This command will initialize Fensalir for working in Gride-H/S in Tannefors,
  Sweden.

  ${BOLD}$ bootstrap --instructions${CLEAR}

  This command will print instructions for how to enable Fensalir
  command in current shell as well as in all future sessions.
EOF
}


# Remove name of this script from _FRIJA_PROGRAM_PATH
_REPO_PATH="${_FRIJA_PROGRAM_PATH%/*}"

# Remove everything before last part of path, i.e. repo name
_REPO_NAME="${_REPO_PATH##*/}"

_FRIJA_IS_SOURCED=""

if [[ ! -v _FENSALIR_HOME ]] \
       || [[ -z "${_FENSALIR_HOME:-}" ]] \
       || [[ ! -d "${_FENSALIR_HOME}" ]];
then
    # We are in a clean environment and need to provide a temporary
    # configuration just for the bootstrap process to work smoothly.
    # This variable hold the name of the Fensalir repo and it will be
    # given a hardcoded value in the fensalir-setup.bash script once
    # the bootstrap process is finished.
    #
    # shellcheck disable=SC2034
    _FENSALIR_REPONAME="${_REPO_NAME}"

    # shellcheck source=./config/fensalir-setup.bash
    source "${_REPO_PATH}/config/fensalir-setup.bash"
fi


# Get _VOLLA_PATH defined
# shellcheck source=./bin/.core_preamble.bash
source "${_REPO_PATH}/bin/.core_preamble.bash"


# Filename for example user configuration file
EXAMPLE_FENSALIRCONFIG="example.fensalirconfig"

# Filename for actual user configuration file
FENSALIRCONFIG=".${EXAMPLE_FENSALIRCONFIG##*.}"

USERINIT="scripts/userinit.bash"


function relative_executable_path()
{
    local commandPath="${1}"
    local commandName="${commandPath##*/}"
    local relativeTo="${2:-${PWD}}"

    commandPath=$(realpath --relative-to="${relativeTo}" "${commandPath}")

    print_debug "commandPath='${commandPath}'"
    print_debug "commandName='${commandName}'"
    print_debug "relativeTo='${relativeTo}'"
    if [[ "${commandPath}" == "${commandName}" ]]; then
        # Path to command is command name itself; we have to add "./"
        # in front of it
        commandPath="./${commandPath}"
    elif [[ ! ("${commandPath}" == "../"* || "${commandPath}" == "/"*) ]]; then
        # Path to command is neither a relative path nor an absolute
        # path; make it a relative path originating from $PWD
        commandPath="./${commandPath}"
    fi

    echo "${commandPath}"
}


function print_init_code()
{
    print_separator "8< Cut Here (start of example .bashrc file) 8<" "${BOLD}"

    local extract=""
    local line=""

    while IFS=$'\n' read -r line; do
        if [[ -n "${extract}" ]]; then
            if [[ "${line}" == '#'*'Cut here'* ]]; then
                extract=""
                break
            else
                printf "%s\\n" "${line}"
            fi
        elif [[ "${line}" == '#'*'Cut here'* ]]; then
            extract="1"
        fi
    done < "${_REPO_PATH}/config/bashrc-example.bash"

    print_separator "8< Cut Here (end of example .bashrc file) 8<" "${BOLD}"
}


function print_init_message()
{
    cat <<EOF 1>&2

${BOLD}FENSALIR (FRIJA AND VOLLA) INITIALIZATION INSTRUCTIONS${CLEAR}
${BOLD}======================================================${CLEAR}
Follow step-by-step instructions below to complete setup of Fensalir.

EOF

    case "${OPERATING_SYSTEM}" in
        "${WINDOWS_OS}")
            cat <<EOF 1>&2
--------------------------------------------------------------------------------
${BOLD}Windows users${CLEAR}, PLEASE re-run ${BOLD}${_FRIJA_PROGRAM_NAME}${CLEAR} with -w/--windows option for further
information, e.g.
  ${BOLD}${BOOTSTRAP_RELATIVE_PATH} --windows${CLEAR}
--------------------------------------------------------------------------------

EOF
            ;;
        "${LINUX_OS}")
            ;;
    esac

    local done="done:"

    local doneInstall=""
    if [[ -e "${_VOLLA_PATH}/${_FENSALIR_SETUP}" ]]; then
        doneInstall="${BOLD}${done^^}${CLEAR}"
    fi

    local doneBashrc=""
    local sourceExpression="source ${FENSALIR_USER_CONFIG_PATH}/${USERINIT}"
    # Solaris grep does not support long options.
    # -c  Count
    #
    # Note that fixed string match can NOT be used and regular
    # expression match must be used instead. This is due to that with
    # fixed string match you can not instruct grep to match from the
    # beginning of the line. Due to this all '.' (dot) characters must
    # be escaped so a match is done against the explicit dot character
    # and not the regexp dot "match any character".
    if (( $(grep -c "^${sourceExpression//./[.]}" "${HOME}/.bashrc") >= 1 ))
    then
        doneBashrc="${BOLD}${done^^}${CLEAR}"
    fi

    cat <<EOF 1>&2
${BOLD}Step by step instructions${CLEAR}
${BOLD}-------------------------${CLEAR}
${doneInstall} 1. Install Fensalir, e.g.
      ${BOLD}$ ./bootstrap --country=SE --site=TN --domain=Gride-H/S${CLEAR}

 2. Check if Frija command works in current shell, e.g.
      ${BOLD}$ source ${_VOLLA_PATH}/${_FENSALIR_SETUP}${CLEAR}
      ${BOLD}$ frija --help${CLEAR}
    If you get a help message continue with Step 2 below.

${doneBashrc} 3. Modify your personal .bashrc to persistently install Fensalir by adding
    the line below to it
      ${BOLD}${sourceExpression}${CLEAR}

 3.1 ${BOLD}Optional:${CLEAR} To get all applications started from your window manager to know
     about for instance the same Git version as is added by Fensalir setup
     script create (unless it already exists) your personal ${BOLD}.bash_profile${CLEAR}
     in your home folder and add the following line to it
       ${BOLD}source "${HOME}/.bashrc"

     This file is read by Bash for all login sessions. Test that
     nothing goes wrong by starting an SSH session to another server in your
     environment.

 3.2 ${BOLD}Optional:${CLEAR} Make a copy of the example Fensalir config file
       ${BOLD}${configHome}/${FENSALIR_EXAMPLE_CONFIG}${CLEAR}
     to one of the file paths below
       A) ${BOLD}${HOME}/${FENSALIRCONFIG}${CLEAR}
       B) ${BOLD}${FENSALIR_USER_CONFIG_PATH}/${FENSALIRCONFIG}${CLEAR}

     ${BOLD}Note:${CLEAR} When Fensalir initializes it first tries to load A) and if it does
           not exist it falls back to B). If none of them exist Fensalir uses
           default settings.

 4 Users also using Windows development environment should run this command
   with '-w/--windows' option and read through the information, e.g.
     ${BOLD}${BOOTSTRAP_RELATIVE_PATH} --windows${CLEAR}

 5. Start a new terminal and check that the frija command works as expected.
    If it does not work as expected revert your changes and troubleshoot.

 6. Clone a ${BOLD}Fensalir Environment${CLEAR} repository, e.g. start with
      ${BOLD}frija fetch --help${CLEAR}

--------------------------------------------------------------------------------
${BOLD}Note:${CLEAR} List of available Fensalir Environment repositories to use
      should be provided by your organization.
${BOLD}Note:${CLEAR} TAB completion should also work for ${UNDERLINE_ON}all${UNDERLINE_OFF} frija commands!
${BOLD}Note:${CLEAR} All frija commands support -h/--help option.

EOF
}


function print_windows_init_message()
{
    cat <<EOF

${BOLD}FRIJA AND VOLLA WINDOWS CONFIGURATION TIP${CLEAR}
${BOLD}=========================================${CLEAR}
To change the look-and-feel of the MinTTY terminal Git Bash uses you can use a
${BOLD}.minttyrc${CLEAR} configuration text file placed in your home folder.

An example ${BOLD}.minttyrc${CLEAR} file is placed in the root of the ${BOLD}${_REPO_NAME}${CLEAR} repo,
i.e.
  ${BOLD}cp ${_VOLLA_PATH}/${_REPO_NAME}/.minttyrc ${HOME}${CLEAR}

If you do this, the next time MinTTY is started it will use the configuration
file ${BOLD}${HOME}.minttyrc${CLEAR} (this is where the settings are stored).

${BOLD}Note:${CLEAR} The example configuration file enables the same copy and paste shortcuts
      as Gnome Terminal uses; Shift+Crtl-C to copy and Shift+Ctrl-V to paste.
      It also turns off cursor blink and enables block cursor.

      Since it is a plain-text file you can modify it to your liking (some of
      the options, but not all, can be set from within MinTTY option dialog.

${BOLD}Note:${CLEAR} Some settings does not seem to work via GUI (like changing or creating
      color palettes). These settings must thus be done via the text
      configuration file.

EOF
}


function print_linux_init_message()
{
    cat <<EOF

${BOLD}FRIJA AND VOLLA LINUX CONFIGURATION TIP${CLEAR}
${BOLD}=======================================${CLEAR}
As of now there are no additional configuration steps for Linux users. :)

EOF
}


# Print either
#
# - Available country values if no parameters are given (or if one,
#   two, or all three are empty strings). Listed country names follow
#   ISO 3166-1 alpha2 two-letter country codes. See for instance
#   Wikipedia for more information. Stored in config/countries file.
#
# - Available site values for given country (no other values given).
#   Listed sites follow the two-letter or three-letter site names;
#   such as "TN" for Tannefors and "JA" for Järfälla, and GPX for
#   Gavião Peixoto in Brazil. Stored in config/<country>_sites files,
#   for instance config/SE_sites file.
#
# - Available domain values for given combination of country and site;
#   Domain names are the assigned names to development environments
#   such as Gride-H/S and LKP. Note that spaces are replaced with '-'
#   (hyphens). Stored in config/<country>_<site>_domains files,
#   for instance config/SE_TN_domains file.
#
#
# First parameter is country; it is optional
#
# Second parameter is site; it is optional, but country must be given
#
# Third parameter is domain; it is optional, but country and site must
# be given
function print_country_site_domain_values()
{
    echo
}


function validate_country_site_domain()
{
    echo
}



country=""
site=""
domain=""
LIST="n"

# Iterate over options in order and nicely split until we see --
while true; do
    case "${1}" in
        -C|--country)
            ensure_option_not_set "Current country" "${country}"
            shift  # Move to next option
            country="${1}"
            ensure_option_argument_set "Current country" "${country}"
            shift  # Move to next option
            ;;
        -S|--site)
            ensure_option_not_set "Current site" "${site}"
            shift  # Move to next option
            site="${1}"
            ensure_option_argument_set "Current site" "${site}"
            shift  # Move to next option
            ;;
        -D|--domain)
            ensure_option_not_set "Current domain" "${domain}"
            shift  # Move to next option
            domain="${1}"
            ensure_option_argument_set "Current domain" "${domain}"
            shift  # Move to next option
            ;;
        -l|--list)
            ensure_boolean_option_not_set "List available values" "${LIST}"
            LIST="y"
            shift
            ;;
        -i|--instructions)
            ensure_option_not_set "Print instructions" "${initMessage}"
            # Print init message and exit
            initMessage="y"
            shift  # Move to next option
            ;;
        -c|--code)
            # Show .bash_profile init code
            print_init_code
            exit 0
            ;;
        -W|--windows)
            print_windows_init_message
            exit 0
            ;;
        -L|--linux)
            print_linux_init_message
            exit 0
            ;;
        -v|--verbose)
            ensure_boolean_option_not_set "Verbose" "${VERBOSE}"
            VERBOSE="y"
            shift  # Move to next option
            ;;
        -h|--help)
            _frija_subcommand_usage
            exit 0
            ;;
        -d|--debug)
            ensure_boolean_option_not_set "Debug" "${DEBUG}"
            DEBUG="y"
            shift
            ;;
        --dry-run)
            # See .core_preamble.bash for more information
            set_dry_run
            shift
            ;;
        -f|--force-os)
            ensure_option_not_set "OS override" "${osOverride}"
            shift  # Move to next option
            osOverride="${1}"
            ensure_option_argument_set "OS override" "${osOverride}"
            shift  # Move to next option
            ;;
        --)
            shift
            break
            ;;
        *)
            print_error "Internal command line parsing error; Current option is '${1}' and rest is '${*}'" 3
            ;;
    esac
done


# Allow user to explicitly override detected OS
if [[ -n "${osOverride}" ]]; then
    OPERATING_SYSTEM="${osOverride}"
fi

if [[ ! -v HOME ]] || [[ -z "${HOME}" ]]; then
    message="Environment variable HOME is unset or empty, please assign "
    message+="it a valid value and retry, aborting."

    # shellcheck disable=SC2086
    print_error "${message}" $_FRIJA_EXIT_OTHER_PROBLEM
fi

# Enable Extended Globbing that give regexp-like matching
# capabilities
shopt -s extglob

# Remove any trailing slashes from $HOME
#
# The white noise-like pattern replacement string below should be
# interpreted like this: '%%' is the "remove matching suffix
# pattern" parameter expansion and '+(...)' introduces an extend
# glob that matches the enclosed pattern one or more times. The
# enclosed pattern '[/]' matches any of the caracters enclosed by
# '[' and ']'; in this case a single slash. Corresponding regular
# expression would be '[/]+'.
HOME="${HOME%%+([/])}"


print_debug "HOME='${HOME}'"
print_debug "DEBUG='${DEBUG}'"
print_debug "OPERATING_SYSTEM='${OPERATING_SYSTEM}'"
print_debug "LIST='${LIST}'"
print_debug "country='${country}'"
print_debug "site='${site}'"
print_debug "domain='${domain}'"

BOOTSTRAP_RELATIVE_PATH=$(relative_executable_path "${_FRIJA_PROGRAM_PATH}")

if [[ -n "${initMessage}" ]]; then
    print_init_message
    exit 0
fi

# Populate arrays holding supported locale configuration values
populate_locale_configuration_data

print_debug "After populate_locale_configuration_data()"
print_debug "country='${country}'"
print_debug "site='${site}'"
print_debug "domain='${domain}'"

if [[ "${LIST}" == "y" ]]; then
    # print valid values for country, or site given country, or domain
    # given country+site
    print_debug "Calling locale_validate_country_site_domain('y' '${country}' '${site}' '${domain}')"
    locale_validate_country_site_domain "${LOCALE_PRINT}" \
                                        "${country}" "${site}" "${domain}"

    if [[ -n "${country}" ]] && [[ -n "${site}" ]] && [[ -n "${domain}" ]]; then
        print_message
        message="The combination country=${BOLD}${country}${CLEAR} "
        message+="site=${BOLD}${site}${CLEAR} domain=${BOLD}${domain}${CLEAR} "
        message+="is valid, now proceed by removing the list option; that is"
        print_message "${message}"

        message="${_FRIJA_USAGE_NAME} -C${country} -S${site} -D${domain}"
        print_message "${BOLD}${message}${CLEAR}"
    fi

    print_message
    exit 0
fi

# Ensure valid values have been assigned to $country, $site, and $domain
locale_validate_country_site_domain "n" "${country}" "${site}" "${domain}"

if [[ -d "${_VOLLA_PATH}/${_REPO_NAME}" ]] && [[ ! -v JENKINS_HOME ]]; then
    message="Fensalir is already installed as "
    message+="'${BOLD}${_VOLLA_PATH}/${_REPO_NAME}${CLEAR}'. "
    message+="Please run "
    message+="'${BOLD}${_FRIJA_USAGE_NAME} --instructions${CLEAR}' "
    message+="and/or remove "
    message+="'${BOLD}${_VOLLA_PATH}${CLEAR}' folder and try again."

    # shellcheck disable=SC2086
    print_error "${message}" $_FRIJA_EXIT_OTHER_PROBLEM
fi


print_message ""
message="Setting up bootstrap environment"
if [[ -v JENKINS_HOME ]]; then
    message+=" (for Jenkins)"
fi
print_message "${message}..."

vollaFolderStructure="${_VOLLA_PATH}/${_REPO_NAME}/bin"
if [[ ! -e "${vollaFolderStructure}" ]]; then
    declare -a command
    command=("${SINGLE}" "Creating dummy volla folder structure" \
                         mkdir --parents "${vollaFolderStructure}")
    run "${command[@]}"
fi

frijaFile="${_VOLLA_PATH}/${_REPO_NAME}/bin/frija"
if [[ ! -e "${frijaFile}" ]]; then
    # Dummy file needed so we can source ${_FENSALIR_SETUP} (it sources
    # this file which is needed for TAB-completion which we will not need
    # right now as we are not interactive on the command line).
    command=("${SINGLE}" "Creating dummy frija file" \
                         touch "${frijaFile}")
    run "${command[@]}"
fi

# $INHIBIT_NOT_FOUND_MESSAGE control behavior in $_FENSALIR_SETUP
# shellcheck disable=SC2034
INHIBIT_NOT_FOUND_MESSAGE="y"
# shellcheck source=./config/fensalir-setup.bash
source "${_REPO_PATH}/config/${_FENSALIR_SETUP}"

# Override definition of _FENSALIR_HOME variable so it points to
# the temporary location of the fensalir repo.
_FENSALIR_HOME="${_REPO_PATH}/bin"


print_message ""
print_message "Bootstrapping real environment for Fensalir..."

print_debug "_VOLLA_PATH='${_VOLLA_PATH}"
print_debug "_REPO_NAME='${_REPO_NAME}"
print_debug "Command: '${_VOLLA_PATH}/${_REPO_NAME:?}'"
if [[ ! -v "JENKINS_HOME" ]]; then
    # Ensure _REPO_NAME never ends with '/' by using :? for expansion
    # Remove the dummy structure we created above to get scripts
    # source-able (yes, the sourced scripts are tricked to believe there
    # is something installed in the correct place)
    command=("${SINGLE}" "Removing dummy volla folder structure" \
                         rm -fr "${_VOLLA_PATH}/${_REPO_NAME:?}")
    run "${command[@]}"

    # Base path is the search path to the Fensalir repo containing
    # this command. That is the name of the command is removed and the
    # folder containing the command from the path. What remains is the
    # _VOLLA_BASE_PATH.
    #
    # Remove shortest suffix matching "/*/*", i.e. last and 2nd last
    # part of path
    _VOLLA_BASE_PATH="${_FENSALIR_HOME%/*}"


    command=("${SINGLE}" "Initializing volla file structure" \
                         mkdir --parents "${_VOLLA_PATH}")
    run "${command[@]}"
fi


# Finally filter config file so $searchString below is assigned the
# name of the Fensalir repo. This is done using sed.

################################################################################
# Transform ${_FENSALIR_SETUP} during copy to $_VOLLA_PATH
#

# sed expression to replace all occurrences of $reponameString with $_REPO_NAME
reponameString="_FENSALIR_REPONAME"
sedReponame="s/^${reponameString}=\".{_REPO_NAME}\"/"
sedReponame+="${reponameString}=\"${_REPO_NAME}\"/"

# sed expression to replace all occurrences of $repohomeString with
# $_VOLLA_PATH/$_REPO_NAME, than is path to Fensalir repo.
#
# As a PATH contain '/' characters we must use another separator
# character then '/' and here we opt to use '%' and cross our fingers
# that the path to Volla does not contain any '%' characters (it
# should not do that).
reporootString="_FENSALIR_ROOT"
sedReporoot="s%^${reporootString}=\".{_REPO_PATH}\"%"
sedReporoot+="${reporootString}=\"${_VOLLA_PATH}/${_REPO_NAME}\"%"

# sed expression to replace all occurrences of $countryString with $country
countryString="export _FRIJA_DEVELOPMENT_COUNTRY"
sedCountry="s/^${countryString}=''/${countryString}=\"${country}\"/"

# sed expression to replace all occurrences of $siteString with $site
siteString="export _FRIJA_DEVELOPMENT_SITE"

# To be extra careful we take precautions that any '/' characters in
# the site name does not cause any problems in the sed expression
# below. See the comment for $sedDomain below for further information.
sedSite="s%^${siteString}=''%${siteString}=\"${site//%/\\%}\"%"

# sed expression to replace all occurrences of $domainString with $domain
domainString="export _FRIJA_DEVELOPMENT_DOMAIN"

# The domain string may contain '/' characters and this will cause
# problems with sed where you usually write 'sed -e s/foo/bar/' where
# the character following 's' is used as the field spearator; in this
# case '/' is used to separate the match part ('foo') from the
# replacement part ('bar').
#
# We could use another character like '%' as the field separator like
# 'sed -e s%foo%bar%' but then we would end up with the same problem
# if there are any '%' caracters in either 'foo' or 'bar'.
#
# Another option is to escape any occurrences of the field separator
# in 'bar' using '\'; assuming bar is "a/b/c" we would then get 'sed
# -e s/foo/a\\/b\\/c/'. This is beacause backslash needs to be escaped
# for Bash to get the backslash character, thus '\\' means a single
# backslash and we end up with '\\/' to escape the slash character.
#
# As this is rapidly approaching something that looks like white noise
# a more readable approach is to combine the two methods outlined
# above. Use another character than '/' as the field separator and
# escape it. Here we have opted to use '%' as the field separator and
# then you instead get 'sed -e s%foo%a/b/c%'; alas we also have to
# escape all occurrences of '%' the replacement string.
#
# This is done useing Bash parameter expansion with string
# replacement, for instance '${var//foo/bar}' will replace all
# occurrences of 'foo' with 'bar' during expansion of $var. Thus to
# replace all occurrences of '%' with '\\%' we simply to
# '${var//%/\\%}'.
#
# Note: Since Bash does not allow '%' in variable names there is no
# need to do anything with $domainString as it is guaranteed to be
# 'safe'.
sedDomain="s%^${domainString}=''%${domainString}=\"${domain//%/\\%}\"%"



## sed expression to replace all occurrences of $countryString with $country
safeCntryString="export _FRIJA_DEVELOPMENT_SAFE_COUNTRY"

# Transform $country by removing all slashes. The intention is to
# create a string that can safely be used in filenames, search paths,
# branch names, and so on.
safeCountry="${country//\//}"

# Expression for replacing the dummy assignment with an actual value
sedSafeCountry="s/^${safeCntryString}=''/${safeCntryString}=\"${safeCountry}\"/"


## sed expression to replace all occurrences of $siteString with $site
safeSiteString="export _FRIJA_DEVELOPMENT_SAFE_SITE"

# Transform $site by removing all slashes. The intention is to
# create a string that can safely be used in filenames, search paths,
# branch names, and so on.
safeSite="${site//\//}"

# Expression for replacing the dummy assignment with an actual value
sedSafeSite="s/^${safeSiteString}=''/${safeSiteString}=\"${safeSite}\"/"


## sed expression to replace all occurrences of $domainString with $domain
safeDmainString="export _FRIJA_DEVELOPMENT_SAFE_DOMAIN"

# Transform $domain by removing all slashes. The intention is to
# create a string that can safely be used in filenames, search paths,
# branch names, and so on.
safeDomain="${domain//\//}"

# Expression for replacing the dummy assignment with an actual value
sedSafeDomain="s/^${safeDmainString}=''/${safeDmainString}=\"${safeDomain}\"/"


# File template for the configuration file. This file is filtered
# below using sed.
configFile="${_FENSALIR_HOME}/../config/${_FENSALIR_SETUP}"


# File to filter using sed
inputFilePath="${configFile}"

# File to store sed result in; remove longest matching prefix "*/"
# from $inputFile, i.e. all path components up to but not including
# the file name itself.
outputFilePath="${_VOLLA_PATH}/${inputFilePath##*/}"

# sed command to execute where output of command is redirected to
# $outputFilePath
command=("${SINGLE}" "${CLEAR}Filtering setup script" "${outputFilePath}" \
                   sed -e "${sedReponame}" \
                       -e "${sedReporoot}" \
                       -e "${sedCountry}" \
                       -e "${sedSite}" \
                       -e "${sedDomain}" \
                       -e "${sedSafeCountry}" \
                       -e "${sedSafeSite}" \
                       -e "${sedSafeDomain}" \
                       "${inputFilePath}")
run_with_redirect "${command[@]}"

#
# Transform section ends here
################################################################################


if [[ ! -v JENKINS_HOME ]]; then
#    print_separator
#    ls -la
#    print_separator
#    cd "${WORKSPACE}"
#    print_message "PWD='${PWD}'"
#    print_message "Moving Fensalir repo to Volla folder"
#    ! mv -f "${_VOLLA_BASE_PATH}" "${_VOLLA_PATH}"
#    #cp -r "${_VOLLA_BASE_PATH}" "${_VOLLA_PATH}"
#    #
#    #message="Moving Fensalir repo to Volla folder: Step 2 (clean up)"
#    #print_message "${message}"
#    #! rm -fr "${_VOLLA_BASE_PATH}"
#else
    command=("${SINGLE}" "Copying Fensalir repo to Volla folder" \
                         cp -r "${_VOLLA_BASE_PATH}" "${_VOLLA_PATH}")
    run "${command[@]}"
fi


# Use print_message instead of here-document to get automatic line
# wrapping.
print_message ""
print_separator
message="${BOLD}Fensalir${CLEAR} (Frija and Volla) "
message+="successfully installed in"
print_message "${message}"
print_message "${BOLD}${_VOLLA_PATH}${CLEAR}"

message="with base locale set to country ${BOLD}${country}${CLEAR}, "
message+="site ${BOLD}${site}${CLEAR}, and domain ${BOLD}${domain}${CLEAR}."
print_message "${message}"
print_separator
print_message ""




if [[ -n "${FENSALIR_USER_CONFIG_PATH}" ]]; then
    message="Setting up Fensalir user init and configuration files"
    print_message "${message}"
    print_message

    command=("${SINGLE}" "Ensuring '${FENSALIR_USER_CONFIG_PATH}' exist" \
                         mkdir -p "${FENSALIR_USER_CONFIG_PATH}/scripts")
    run "${command[@]}"

    # Path to folder containing scripts to be copied to users
    # configuration folder
    userfiles="${_FENSALIR_HOME}/../config/userfiles"

    # Target example user configuration file
    exampleConfigFile="${FENSALIR_USER_CONFIG_PATH}/${EXAMPLE_FENSALIRCONFIG}"

    # sed expression to replace all occurrences of
    # _FENSALIR_CONFIG_ with value of ${FENSALIRCONFIG}
    sedFensalirConfig="s/_FENSALIRCONFIG_/${FENSALIRCONFIG}/"

    configHome="${FENSALIR_USER_CONFIG_PATH/${HOME}\//}"
    # sed expression to replace all occurrences of
    # _FENSALIR_CONFIG_ with value of ${_FENSALIR_CONFIG}
    sedFensalirConfigHome="s;_FENSALIR_USER_CONFIG_HOME_;${configHome};"


    # Filter template example configuration file and store it as a
    # temporary copy in the $FENSALIR_USER_CONFIG_PATH folder

    inputFilePath="${userfiles}/${EXAMPLE_FENSALIRCONFIG}"
    outputFilePath="${exampleConfigFile}.tmp"

    # Use sed command to filter $inputFilePath to $outputFilePath.
    # Note that the content of this variable is reused below when
    # temporary file is renamed.
    command=("${SINGLE}" "${CLEAR}Filtering example config" \
                         "${outputFilePath}" \
                         sed -e "${sedFensalirConfig}" \
                         -e "${sedFensalirConfigHome}" \
                         "${inputFilePath}")
    run_with_redirect "${command[@]}"

    if [[ -e "${exampleConfigFile}" ]]; then
        if ! diff "${outputFilePath}" "${exampleConfigFile}" 1>&2 >/dev/null
        then
            warning="Existing Fensalir example configuration file "
            warning+="'${exampleConfigFile}' differs from new version."

            message="Please compare new version with backup copy and update "
            message+="personal Fensalir configuration settings as necessary."

            print_warning "${warning}" "${message}"

            # To force cp command to create a backup for us we have to
            # create a copy of the exsiting file first
            command=("${SINGLE}" "" \
                                 cp "${exampleConfigFile}" \
                                 "${exampleConfigFile}.old")
            run "${command[@]}"

            command=("${SINGLE}" \
                         "Creating backup of existing example config file" \
                         cp "--backup=numbered" "--force" \
                         "${exampleConfigFile}.old" \
                         "${exampleConfigFile}")
            run "${command[@]}"

            # Cleaning up
            command=("${SINGLE}" "Removing existing example config file" \
                                 rm "--force" \
                                 "${exampleConfigFile}" \
                                 "${exampleConfigFile}.old")
            run "${command[@]}"

            command=("${SINGLE}" \
                         "Clearing '${FENSALIR_USER_CONFIG_PATH}/scripts'" \
                         rm -fr "${FENSALIR_USER_CONFIG_PATH}/scripts")
            run "${command[@]}"

            # Recreate scripts folder we just removed
            command=("${SINGLE}" \
                         "" \
                         mkdir -p "${FENSALIR_USER_CONFIG_PATH}/scripts")
            run "${command[@]}"
        fi
    fi

    # Expand glob by creating an array
    files=("${userfiles}"/*)
    command=("${SINGLE}" "Copying Fensalir init and configuration files" \
                         cp "--recursive" "--backup=numbered" "--force" \
                         "${files[@]}" \
                         "${FENSALIR_USER_CONFIG_PATH}")
    run "${command[@]}"

    # Rename temporary filtered example config file, effectively
    # replacing the one originating from the repo with placeholder
    # fields
    command=("${SINGLE}" "" \
                         mv "${outputFilePath}" "${exampleConfigFile}")
    run "${command[@]}"


    # Filter template userinit file and store it in the
    # $FENSALIR_USER_CONFIG_PATH folder

    inputFilePath="${userfiles}/${USERINIT}"
    outputFilePath="${FENSALIR_USER_CONFIG_PATH}/${USERINIT}"

    # Use sed command to filter $inputFilePath to $outputFilePath.
    command=("${SINGLE}" "${CLEAR}Filtering userconfig script" \
                         "${outputFilePath}" \
                         sed -e "${sedFensalirConfig}" \
                         "${inputFilePath}")
    run_with_redirect "${command[@]}"

    # Check if there already exist a user configuration file and if so
    # inform user that it might need to be updated

    configFile=""
    if [[ -r "${HOME}/${FENSALIRCONFIG}" ]]; then
        configFile="${HOME}/${FENSALIRCONFIG}"
    elif [[ -r "${FENSALIR_USER_CONFIG_PATH}/${FENSALIRCONFIG}" ]]; then
        configFile="${FENSALIR_USER_CONFIG_PATH}/${FENSALIRCONFIG}"
    fi

    if [[ -n "${configFile}" ]]; then
        if ! diff "${exampleConfigFile}" "${configFile}" 1>&2 >/dev/null
        then
            warning="Discovered an old Fensalir user configuration "
            warning+="file ('${configFile}')."

            message="Please review '${BOLD}${exampleConfigFile}${CLEAR}' "
            message+="and update your personal Fensalir user configuration "
            message+="settings as necessary."

            print_warning "${warning}" "${message}"
        fi
    fi

    print_message
    print_double_separator
    print_message "Installation of Fensalir finished successfully!"
    print_double_separator

    print_message
    message="Please continue with initialization instructions, e.g."
    print_message "${message}"

    message="  ${BOLD}${BOOTSTRAP_RELATIVE_PATH} --instructions${CLEAR}"
    print_message "${message}"
    print_message ""
fi
