#!/bin/bash --norc

# More safety, by turning some bugs into errors. Without 'errexit' you
# don't need ! and can replace PIPESTATUS with a simple $?, but then
# we would need to remember to explcitly test return status for each
# command. Note that ! hides the exit status of the executed command.
# Due to this we have to use PIPESTATUS to get to it and no history
# expansion when using '!' in for instance echo strings.
set -o errexit -o errtrace -o pipefail -o noclobber -o nounset +o history

# Path to this script
_FRIJA_PROGRAM_PATH=$(readlink -e "${0}")
_BOOTSTRAP_PATH="${_FRIJA_PROGRAM_PATH}"

# Set $FENSALIR_USERCONFIG_PATH unless $JENKINS_HOME is set
if [[ ! -v JENKINS_HOME ]]; then

    _unameOut="$(uname -s)"
    if [[ "${_unameOut}" == "SunOS" ]]; then
        cat <<EOF

ERROR: Fensalir non-Jenkins bootstrap process not supported on Solaris.

EOF
        exit 1
    fi
fi


# Command line options for this script

# - Option followed by : indicate a required argument to option
# - Option followed by :: indicate an optional argument to option
_FRIJA_SUBCOMMAND_OPTIONS="C:S:D:licWLvhdf:"

# - Option followed by : indicate a required argument to option
# - Option followed by :: indicate an optional argument to option
# - Comma (,) separates multiple long options
_FRIJA_SUBCOMMAND_LONGOPTS="country:,site:,domain:,list,instructions,code,windows,linux,verbose,help,debug,dry-run,force-os:"



# Internal states
DRY_RUN="n"
VERBOSE="n"
DEBUG="n"
osOverride=""
initMessage=""

# Silence warning from shellcheck about $BOLD not being assigned. It
# will be assigned when .core_preamble.bash is sourced below.
BOLD=""

function _frija_subcommand_usage()
{
    cat <<EOF
${BOLD}Usage:${CLEAR} ${_FRIJA_USAGE_NAME} OPTION

  Used for bootstraping installation of the Fensalir; ${BOLD}frija${CLEAR} and ${BOLD}volla${CLEAR}.

  As part of the bootstrapping process you must also set the country,
  site, and development domain you are working in.

  If you are looking for a way to update Fensalir repo, then please use
  ${BOLD}frija update${CLEAR} command instead.

${BOLD}Options:${CLEAR}
  -CCOUNTRY,          country you are located in as COUNTRY
   --country=COUNTRY
  -SSITE,             site SITE located in COUNTRY you are located at
    --site=SITE
  -DDOMAIN,           development domain DOMAIN (located in COUNTRY and SITE)
    --domain=DOMAIN      you are working in
  -l, --list          override default behavior of setting by instead listing
                        available values;
                          - if no country given, then countries are listed
                          - if only country given, then list sites
                          - if country+site given, then list domains
                          - if country+site+domain given, then verify combo
  -i, --instructions  print instructions for how to enable Fensalir
                        command in current shell as well as in all future
                        sessions
  -W, --windows       print Windows-specific instructions
  -L, --linux         print Linux-specific instructions
  -v, --verbose       verbose output
  -h, --help          print this message
  --debug             enable debug printouts
                        ${BOLD}Note:${CLEAR} Debug messages are prefixed with
                              "*** LINE  " where LINE is current line
                              number and written to stderr.
  -d, --dry-run       just echo command lines instead of executing them
  -fOS, --force=OS    force command to assume given OS instead of detected OS

${BOLD}Examples:${CLEAR}
  ${BOLD}$ bootstrap --country=SE --site=TN --domain=Gride-H/S${CLEAR}

  This command will initialize Fensalir for working in Gride-H/S in Tannefors,
  Sweden.

  ${BOLD}$ bootstrap --instructions${CLEAR}

  This command will print instructions for how to enable Fensalir
  command in current shell as well as in all future sessions.
EOF
}


# Remove name of this script from _FRIJA_PROGRAM_PATH
_REPOPATH_="${_FRIJA_PROGRAM_PATH%/*}"

# Remove everything before last part of path, i.e. repo name
_REPONAME_="${_REPOPATH_##*/}"

_FRIJA_IS_SOURCED=""

if [[ ! -v _FENSALIR_HOME ]] \
       || [[ -z "${_FENSALIR_HOME:-}" ]] \
       || [[ ! -d "${_FENSALIR_HOME}" ]];
then
    # We are in a clean environment and need to provide a temporary
    # configuration just for the bootstrap process to work smoothly.
    # This variable hold the name of the Fensalir repo and it will be
    # given a hardcoded value in the fensalir-setup.bash script once
    # the bootstrap process is finished.
    #
    # shellcheck disable=SC2034
    _FENSALIR_REPONAME="${_REPONAME_}"

    # shellcheck source=./config/fensalir-setup.bash
    source "${_REPOPATH_}/config/userfiles/scripts/fensalir-identify-os.bash"

    # shellcheck source=./config/fensalir-setup.bash
    source "${_REPOPATH_}/config/fensalir-setup.bash"
fi


# Get _VOLLA_PATH defined
#
# shellcheck source=./bin/.core_preamble.bash
source "${_REPOPATH_}/bin/.core_preamble.bash"

# Get common shared setup functionality
#
# shellcheck source=./bin/.fensalir_setup_support.bash
source "${_REPOPATH_}/bin/.fensalir_setup_support.bash"


if [[ -v JENKINS_HOME ]]; then
    # When in Jenkins environment we set $FENSALIR_USERCONFIG_PATH to
    # an empty string to inhibit parts of this script
    FENSALIR_USERCONFIG_PATH=""
fi


function relative_executable_path()
{
    local commandPath="${1}"
    local commandName="${commandPath##*/}"
    local relativeTo="${2:-${PWD}}"

    commandPath=$(realpath --relative-to="${relativeTo}" "${commandPath}")

    print_debug "commandPath='${commandPath}'"
    print_debug "commandName='${commandName}'"
    print_debug "relativeTo='${relativeTo}'"
    if [[ "${commandPath}" == "${commandName}" ]]; then
        # Path to command is command name itself; we have to add "./"
        # in front of it
        commandPath="./${commandPath}"
    elif [[ ! ("${commandPath}" == "../"* || "${commandPath}" == "/"*) ]]; then
        # Path to command is neither a relative path nor an absolute
        # path; make it a relative path originating from $PWD
        commandPath="./${commandPath}"
    fi

    echo "${commandPath}"
}


function print_init_message()
{
    cat <<EOF 1>&2

${BOLD}FENSALIR (FRIJA AND VOLLA) INITIALIZATION INSTRUCTIONS${CLEAR}
${BOLD}======================================================${CLEAR}
Follow step-by-step instructions below to complete setup of Fensalir.

EOF

    case "${_FENSALIR_CURRENT_OS}" in
        "${_FENSALIR_WINDOWS}")
            cat <<EOF 1>&2
--------------------------------------------------------------------------------
${BOLD}Windows users${CLEAR}, PLEASE re-run ${BOLD}${_FRIJA_PROGRAM_NAME}${CLEAR} with -w/--windows option for further
information, e.g.
  ${BOLD}${BOOTSTRAP_RELATIVE_PATH} --windows${CLEAR}
--------------------------------------------------------------------------------

EOF
            ;;
        "${_FENSALIR_LINUX}")
            ;;
    esac

    local done="done:"

    local doneInstall=""
    if [[ -e "${_VOLLA_PATH}/${_FENSALIR_SETUP}" ]]; then
        doneInstall="${BOLD}${done^^}${CLEAR}"
    fi

    local doneBashrc=""

    # Build Bash source expression to use in .bashrc so the resulting
    # string will look something like
    #
    # source ${HOME}/.config/Fensalir/scripts/userinit.bash
    #
    # Since $FENSALIR_USERINIT_PATH contain the expanded value of
    # $HOME it has to be removed from the string; this is done using
    # '#' in the parameter expansion. Then the explicit '${HOME}' is
    # added to the string without triggering an expansion of it; this
    # is done by escaping the '$' in '${HOME}'.
    #
    # Note that due to the need for parameter expansion (must be done
    # within double-quotes to avoid potential word splitting) in
    # combination with that explicit double-quotes must be included in
    # the resulting string these must also be escaped using
    # backslashes.
    local sourceExpression="source \"\${HOME}"
    sourceExpression+="${FENSALIR_USERINIT_PATH#${HOME}}\""

    # Solaris grep does not support long options.
    # -c  Count
    #
    # Note that fixed string match can NOT be used and regular
    # expression match must be used instead. This is due to that with
    # fixed string match you can not instruct grep to match from the
    # beginning of the line. Due to this all '.' (dot) characters must
    # be escaped so a match is done against the explicit dot character
    # and not the regexp dot "match any character".
    if (( $(grep -c "^${sourceExpression//./[.]}" "${HOME}/.bashrc") >= 1 ))
    then
        doneBashrc="${BOLD}${done^^}${CLEAR}"
    fi

    local configHome="${FENSALIR_USERCONFIG_PATH}"
    if [[ "${configHome}" == "${HOME}/"* ]]; then
        # shellcheck disable=SC2016
        configHome='${HOME}/'"${configHome/${HOME}\//}"
    fi

    cat <<EOF 1>&2
${BOLD}Step by step instructions${CLEAR}
${BOLD}-------------------------${CLEAR}
${doneInstall} 1. Install Fensalir, e.g.
      ${BOLD}$ ./bootstrap --country=SE --site=TN --domain=Gride-H/S${CLEAR}

${BOLD}*${CLEAR}2. Check if Frija command works in current shell, e.g.
      ${BOLD}$ source ${_VOLLA_PATH}/${_FENSALIR_SETUP}${CLEAR}
      ${BOLD}$ frija --help${CLEAR}
    If you get a help message continue with Step 2 below.

${doneBashrc} 3. Modify your personal .bashrc to persistently install Fensalir by adding
    the line below to it
      ${BOLD}${sourceExpression}${CLEAR}

${BOLD}*${CLEAR}3.1 ${BOLD}Optional:${CLEAR} To get all applications started from your window manager to know
     about for instance the same Git version as is added by Fensalir setup
     script create (unless it already exists) your personal ${BOLD}.bash_profile${CLEAR}
     in your home folder and add the following line to it
       ${BOLD}source "${HOME}/.bashrc"

     This file is read by Bash for all login sessions. Test that
     nothing goes wrong by starting an SSH session to another server in your
     environment.

${BOLD}*${CLEAR}3.2 ${BOLD}Optional:${CLEAR} Make a copy of the example Fensalir config file
       ${BOLD}${configHome}/${FENSALIR_EXAMPLE_CONFIG}${CLEAR}
     to one of the file paths below
       A) ${BOLD}${HOME}/${FENSALIR_USERCONFIG_FILE}${CLEAR}
       B) ${BOLD}${configHome}/${FENSALIR_USERCONFIG_FILE}${CLEAR}

     ${BOLD}Note:${CLEAR} When Fensalir initializes it first tries to load A) and if it does
           not exist it falls back to B). If none of them exist Fensalir uses
           default settings.

${BOLD}*${CLEAR}4 Users also using Windows development environment should run this command
   with '-w/--windows' option and read through the information, e.g.
     ${BOLD}${BOOTSTRAP_RELATIVE_PATH} --windows${CLEAR}

${BOLD}*${CLEAR}5. Start a new terminal and check that the frija command works as expected.
    If it does not work as expected revert your changes and troubleshoot.

${BOLD}*${CLEAR}6. Clone a ${BOLD}Fensalir Environment${CLEAR} repository, e.g. start with
      ${BOLD}fensalir fetch --help${CLEAR}

${BOLD}*${CLEAR} Marks steps that this script can ${UNDERLINE_ON}NOT${UNDERLINE_OFF} detect whether they have
  been ${BOLD}done${CLEAR} or ${BOLD}not done${CLEAR}.
--------------------------------------------------------------------------------
${BOLD}Note:${CLEAR} After Fensalir has been installed it can be updated using
      the ${BOLD}frija update${CLEAR} command.
${BOLD}Note:${CLEAR} List of available Fensalir Environment repositories to use
      should be provided by your organization.
${BOLD}Note:${CLEAR} TAB completion should also work for ${UNDERLINE_ON}all${UNDERLINE_OFF} frija commands!
${BOLD}Note:${CLEAR} All frija commands support -h/--help option.

EOF
}


function print_windows_init_message()
{
    cat <<EOF

${BOLD}FRIJA AND VOLLA WINDOWS CONFIGURATION TIP${CLEAR}
${BOLD}=========================================${CLEAR}
To change the look-and-feel of the MinTTY terminal Git Bash uses you can use a
${BOLD}.minttyrc${CLEAR} configuration text file placed in your home folder.

An example ${BOLD}.minttyrc${CLEAR} file is placed in the root of the ${BOLD}${_REPONAME_}${CLEAR} repo,
i.e.
  ${BOLD}cp ${_VOLLA_PATH}/${_REPONAME_}/.minttyrc ${HOME}${CLEAR}

If you do this, the next time MinTTY is started it will use the configuration
file ${BOLD}${HOME}.minttyrc${CLEAR} (this is where the settings are stored).

${BOLD}Note:${CLEAR} The example configuration file enables the same copy and paste shortcuts
      as Gnome Terminal uses; Shift+Crtl-C to copy and Shift+Ctrl-V to paste.
      It also turns off cursor blink and enables block cursor.

      Since it is a plain-text file you can modify it to your liking (some of
      the options, but not all, can be set from within MinTTY option dialog.

${BOLD}Note:${CLEAR} Some settings does not seem to work via GUI (like changing or creating
      color palettes). These settings must thus be done via the text
      configuration file.

EOF
}


function print_linux_init_message()
{
    cat <<EOF

${BOLD}FRIJA AND VOLLA LINUX CONFIGURATION TIP${CLEAR}
${BOLD}=======================================${CLEAR}
As of now there are no additional configuration steps for Linux users. :)

EOF
}


# Print either
#
# - Available country values if no parameters are given (or if one,
#   two, or all three are empty strings). Listed country names follow
#   ISO 3166-1 alpha2 two-letter country codes. See for instance
#   Wikipedia for more information. Stored in config/countries file.
#
# - Available site values for given country (no other values given).
#   Listed sites follow the two-letter or three-letter site names;
#   such as "TN" for Tannefors and "JA" for Järfälla, and GPX for
#   Gavião Peixoto in Brazil. Stored in config/<country>_sites files,
#   for instance config/SE_sites file.
#
# - Available domain values for given combination of country and site;
#   Domain names are the assigned names to development environments
#   such as Gride-H/S and LKP. Note that spaces are replaced with '-'
#   (hyphens). Stored in config/<country>_<site>_domains files,
#   for instance config/SE_TN_domains file.
#
#
# First parameter is country; it is optional
#
# Second parameter is site; it is optional, but country must be given
#
# Third parameter is domain; it is optional, but country and site must
# be given
function print_country_site_domain_values()
{
    echo
}


function validate_country_site_domain()
{
    echo
}



country=""
site=""
domain=""
LIST="n"

# Iterate over options in order and nicely split until we see --
while true; do
    case "${1}" in
        -C|--country)
            ensure_option_not_set "Current country" "${country}"
            shift  # Move to next option
            country="${1}"
            ensure_option_argument_set "Current country" "${country}"
            shift  # Move to next option
            ;;
        -S|--site)
            ensure_option_not_set "Current site" "${site}"
            shift  # Move to next option
            site="${1}"
            ensure_option_argument_set "Current site" "${site}"
            shift  # Move to next option
            ;;
        -D|--domain)
            ensure_option_not_set "Current domain" "${domain}"
            shift  # Move to next option
            domain="${1}"
            ensure_option_argument_set "Current domain" "${domain}"
            shift  # Move to next option
            ;;
        -l|--list)
            ensure_boolean_option_not_set "List available values" "${LIST}"
            LIST="y"
            shift
            ;;
        -i|--instructions)
            ensure_option_not_set "Print instructions" "${initMessage}"
            # Print init message and exit
            initMessage="y"
            shift  # Move to next option
            ;;
        -W|--windows)
            print_windows_init_message
            exit 0
            ;;
        -L|--linux)
            print_linux_init_message
            exit 0
            ;;
        -v|--verbose)
            ensure_boolean_option_not_set "Verbose" "${VERBOSE}"
            VERBOSE="y"
            shift  # Move to next option
            ;;
        -h|--help)
            _frija_subcommand_usage
            exit 0
            ;;
        -d|--debug)
            ensure_boolean_option_not_set "Debug" "${DEBUG}"
            DEBUG="y"
            shift
            ;;
        --dry-run)
            # See .core_preamble.bash for more information
            set_dry_run
            shift
            ;;
        -f|--force-os)
            ensure_option_not_set "OS override" "${osOverride}"
            shift  # Move to next option
            osOverride="${1}"
            ensure_option_argument_set "OS override" "${osOverride}"
            shift  # Move to next option
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Internal command line parsing error"
            echo "Current option is '${1}' and rest is"
            echo "$@"
            exit "$_FRIJA_EXIT_INTERNAL_ERROR"
            ;;
    esac
done


# Allow user to explicitly override detected OS
if [[ -n "${osOverride}" ]]; then
    _FENSALIR_CURRENT_OS="${osOverride}"
fi

if [[ ! -v HOME ]] || [[ -z "${HOME}" ]]; then
    message="Environment variable HOME is unset or empty, please assign "
    message+="it a valid value and retry, aborting."

    # shellcheck disable=SC2086
    print_error "${message}" $_FRIJA_EXIT_OTHER_PROBLEM
fi

# Enable Extended Globbing that give regexp-like matching
# capabilities
shopt -s extglob

# Remove any trailing slashes from $HOME
#
# The white noise-like pattern replacement string below should be
# interpreted like this: '%%' is the "remove matching suffix
# pattern" parameter expansion and '+(...)' introduces an extend
# glob that matches the enclosed pattern one or more times. The
# enclosed pattern '[/]' matches any of the caracters enclosed by
# '[' and ']'; in this case a single slash. Corresponding regular
# expression would be '[/]+'.
HOME="${HOME%%+([/])}"


print_debug "HOME='${HOME}'"
print_debug "DEBUG='${DEBUG}'"
print_debug "_FENSALIR_CURRENT_OS='${_FENSALIR_CURRENT_OS}'"
print_debug "LIST='${LIST}'"
print_debug "country='${country}'"
print_debug "site='${site}'"
print_debug "domain='${domain}'"

BOOTSTRAP_RELATIVE_PATH=$(relative_executable_path "${_FRIJA_PROGRAM_PATH}")

if [[ -n "${initMessage}" ]]; then
    print_init_message
    exit 0
fi

# Populate arrays holding supported locale configuration values
populate_locale_configuration_data

print_debug "After populate_locale_configuration_data()"
print_debug "country='${country}'"
print_debug "site='${site}'"
print_debug "domain='${domain}'"

if [[ "${LIST}" == "y" ]]; then
    # print valid values for country, or site given country, or domain
    # given country+site
    print_debug "Calling locale_validate_country_site_domain('y' '${country}' '${site}' '${domain}')"
    locale_validate_country_site_domain "${LOCALE_PRINT}" \
                                        "${country}" "${site}" "${domain}"

    if [[ -n "${country}" ]] && [[ -n "${site}" ]] && [[ -n "${domain}" ]]; then
        print_message
        message="The combination country=${BOLD}${country}${CLEAR} "
        message+="site=${BOLD}${site}${CLEAR} domain=${BOLD}${domain}${CLEAR} "
        message+="is valid, now proceed by removing the list option; that is"
        print_message "${message}"

        message="${_FRIJA_USAGE_NAME} -C${country} -S${site} -D${domain}"
        print_message "${BOLD}${message}${CLEAR}"
    fi

    print_message
    exit 0
fi

# Ensure valid values have been assigned to $country, $site, and $domain
locale_validate_country_site_domain "n" "${country}" "${site}" "${domain}"

if [[ -d "${_VOLLA_PATH}/${_REPONAME_}" ]] && [[ ! -v JENKINS_HOME ]]; then
    message="Fensalir is already installed as "
    message+="'${BOLD}${_VOLLA_PATH}/${_REPONAME_}${CLEAR}'. "
    message+="Please run "
    message+="'${BOLD}${_FRIJA_USAGE_NAME} --instructions${CLEAR}' "
    message+="and/or remove "
    message+="'${BOLD}${_VOLLA_PATH}${CLEAR}' folder and try again."

    # shellcheck disable=SC2086
    print_error "${message}" $_FRIJA_EXIT_OTHER_PROBLEM
fi


print_message ""
message="Setting up bootstrap environment"
if [[ -v JENKINS_HOME ]]; then
    message+=" (for Jenkins)"
fi
print_message "${message}..."

vollaFolderStructure="${_VOLLA_PATH}/${_REPONAME_}/bin"
if [[ ! -e "${vollaFolderStructure}" ]]; then
    declare -a command
    command=("${SINGLE}" "Creating dummy volla folder structure" \
                         mkdir --parents "${vollaFolderStructure}")
    run "${command[@]}"
fi

frijaFile="${_VOLLA_PATH}/${_REPONAME_}/bin/frija"
if [[ ! -e "${frijaFile}" ]]; then
    # Dummy file needed so we can source ${_FENSALIR_SETUP} (it sources
    # this file which is needed for TAB-completion which we will not need
    # right now as we are not interactive on the command line).
    command=("${SINGLE}" "Creating dummy frija file" \
                         touch "${frijaFile}")
    run "${command[@]}"
fi

# $INHIBIT_NOT_FOUND_MESSAGE control behavior in $_FENSALIR_SETUP
# shellcheck disable=SC2034
INHIBIT_NOT_FOUND_MESSAGE="y"
# shellcheck source=./config/fensalir-setup.bash
source "${_REPOPATH_}/config/${_FENSALIR_SETUP}"

# Override definition of _FENSALIR_HOME variable so it points to
# the temporary location of the fensalir repo.
_FENSALIR_HOME="${_REPOPATH_}/bin"


print_message ""
print_message "Bootstrapping real environment for Fensalir..."

print_debug "_VOLLA_PATH='${_VOLLA_PATH}"
print_debug "_REPONAME_='${_REPONAME_}"
print_debug "Command: '${_VOLLA_PATH}/${_REPONAME_:?}'"
if [[ ! -v "JENKINS_HOME" ]]; then
    # Ensure _REPO_NAME never ends with '/' by using :? for expansion
    # Remove the dummy structure we created above to get scripts
    # source-able (yes, the sourced scripts are tricked to believe there
    # is something installed in the correct place)
    command=("${SINGLE}" "Removing dummy volla folder structure" \
                         rm -fr "${_VOLLA_PATH}/${_REPONAME_:?}")
    run "${command[@]}"

    # Base path is the search path to the Fensalir repo containing
    # this command. That is the name of the command is removed and the
    # folder containing the command from the path. What remains is the
    # _VOLLA_BASE_PATH.
    #
    # Remove shortest suffix matching "/*/*", i.e. last and 2nd last
    # part of path
    _VOLLA_BASE_PATH="${_FENSALIR_HOME%/*}"


    command=("${SINGLE}" "Initializing volla file structure" \
                         mkdir --parents "${_VOLLA_PATH}")
    run "${command[@]}"
fi


# Finally filter config file so $searchString below is assigned the
# name of the Fensalir repo. This is done using sed.
repopath="${_VOLLA_PATH}/${_REPONAME_}"
transform_fensalir_setup "${repopath}" \
                         "${_REPOPATH_}" \
                         "${country}" \
                         "${site}" \
                         "${domain}"


if [[ ! -v JENKINS_HOME ]]; then
#    print_separator
#    ls -la
#    print_separator
#    cd "${WORKSPACE}"
#    print_message "PWD='${PWD}'"
#    print_message "Moving Fensalir repo to Volla folder"
#    ! mv -f "${_VOLLA_BASE_PATH}" "${_VOLLA_PATH}"
#    #cp -r "${_VOLLA_BASE_PATH}" "${_VOLLA_PATH}"
#    #
#    #message="Moving Fensalir repo to Volla folder: Step 2 (clean up)"
#    #print_message "${message}"
#    #! rm -fr "${_VOLLA_BASE_PATH}"
#else
    command=("${SINGLE}" "Copying Fensalir repo to Volla folder" \
                         cp -r "${_VOLLA_BASE_PATH}" "${_VOLLA_PATH}")
    run "${command[@]}"
fi


# Use print_message instead of here-document to get automatic line
# wrapping.
print_message ""
print_separator
message="${BOLD}Fensalir${CLEAR} (Frija and Volla) "
message+="successfully installed in"
print_message "${message}"
print_message "${BOLD}${_VOLLA_PATH}${CLEAR}"

message="with base locale set to country ${BOLD}${country}${CLEAR}, "
message+="site ${BOLD}${site}${CLEAR}, and domain ${BOLD}${domain}${CLEAR}."
print_message "${message}"
print_separator
print_message


if [[ -n "${FENSALIR_USERCONFIG_PATH}" ]]; then
    message="Setting up Fensalir user init and configuration files"
    print_message "${message}"
    print_message

    update_user_config "${repopath}"

    print_message
    print_double_separator
    print_message "Installation of Fensalir finished successfully!"
    print_double_separator

    print_message
    message="Please continue with initialization instructions, e.g."
    print_message "${message}"

    message="  ${BOLD}${BOOTSTRAP_RELATIVE_PATH} --instructions${CLEAR}"
    print_message "${message}"
    print_message ""
fi
