#!/bin/bash

# More safety, by turning some bugs into errors. Without 'errexit' you
# don't need ! and can replace PIPESTATUS with a simple $?, but then
# we would need to remember to explcitly test return status for each
# command. Note that ! hides the exit status of the executed command.
# Due to this we have to use PIPESTATUS to get to it and no history
# expansion when using '!' in for instance echo strings.
set -o errexit -o pipefail -o noclobber -o nounset +o history

# Path to this script
_FRIJA_PROGRAM_PATH=$(readlink -e "${0}")
_BOOTSTRAP_PATH="${_FRIJA_PROGRAM_PATH}"


# Command line options for this script

# - Option followed by : indicate a required argument to option
# - Option followed by :: indicate an optional argument to option
_FRIJA_SUBCOMMAND_OPTIONS="icwlvhdDf:"

# - Option followed by : indicate a required argument to option
# - Option followed by :: indicate an optional argument to option
# - Comma (,) separates multiple long options
_FRIJA_SUBCOMMAND_LONGOPTS="instructions,code,windows,linux,verbose,help,debug,dry-run,force-os:"



# Internal states
DRY_RUN="n"
VERBOSE="n"
DEBUG="n"
osOverride=""
initMessage=""


function _frija_subcommand_usage()
{
    cat <<EOF
${BOLD}Usage:${CLEAR} ${_FRIJA_USAGE_NAME} OPTION

  Used for bootstraping installation of the metadata tools; ${BOLD}frija${CLEAR} and ${BOLD}volla${CLEAR}.

  If you are looking for a way to update metadata tools repo, then please use
  frija update command instead.

${BOLD}Options:${CLEAR}
  -i, --instructions  print instructions for how to enable metadata tools
                        command in current shell as well as in all future
                        sessions
  -c, --code          just show the Frija initialization code for .bash_profile
  -w, --windows       print Windows-specific instructions
  -l, --linux         print Linux-specific instructions
  -v, --verbose       verbose output
  -h, --help          print this message
  -d, --debug         enable debug printouts
                        ${BOLD}Note:${CLEAR} Debug messages are prefixed with
                              "*** LINE  " where LINE is current line
                              number and written to stderr.
  -D, --dry-run       just echo command lines instead of executing them
  -fOS, --force=OS    force command to assume given OS instead of detected OS
EOF
}


# Remove name of this script from _FRIJA_PROGRAM_PATH
_REPO_PATH="${_FRIJA_PROGRAM_PATH%/*}"

# Remove everything before last part of path, i.e. repo name
_REPO_NAME="${_REPO_PATH##*/}"

# These variables must be defined before .core_preamble.bash can be
# sourced
_FRIJA_IS_SOURCED=""
METADATATOOLS_HOME="${_REPO_PATH}/bin"


# Get _VOLLA_PATH defined
# shellcheck source=./bin/.core_preamble.bash
source "${_REPO_PATH}/bin/.core_preamble.bash"


# NOTE: Assume there is a SINGLE configuration file in this folder
configFile=("${METADATATOOLS_HOME}/../config/"*".bash")
configFileName="${configFile[0]##*/}"



function relative_executable_path()
{
    local commandPath="${1}"
    local commandName="${commandPath##*/}"
    local relativeTo="${2:-${PWD}}"

    commandPath=$(realpath --relative-to="${relativeTo}" "${commandPath}")

    print_debug "commandPath='${commandPath}'"
    print_debug "commandName='${commandName}'"
    print_debug "relativeTo='${relativeTo}'"
    if [[ "${commandPath}" == "${commandName}" ]]; then
        # Path to command is command name itself; we have to add "./"
        # in front of it
        commandPath="./${commandPath}"
    elif [[ ! ("${commandPath}" == "../"* || "${commandPath}" == "/"*) ]]; then
        # Path to command is neither a relative path nor an absolute
        # path; make it a relative path originating from $PWD
        commandPath="./${commandPath}"
    fi

    echo "${commandPath}"
}


function print_init_code()
{
    print_separator "8< Cut Here (start of script snippet to include in .bash_profile) 8<" "${BOLD}"

    cat <<EOF

############################
# Frija initialization start
#
_unameOut="\$(uname -s)"
case "\${_unameOut}" in
    Linux*)
        # Bash completion support for Bash 4.1+
        # If you do not want this, either comment all lines in below
        # if-statement or remove them alltogether.
        if [[ "\${BASH_VERSION}" =~ 4[.] ]]; then
            # shellcheck disable=SC2034
            BASH_COMPLETION_VERSION=2.1
            if [[ -r "/p/avionics-tools/opt/bash-completion-2.1/etc/profile.d/bash_completion.sh" ]]; then
	        source /p/avionics-tools/opt/bash-completion-2.1/etc/profile.d/bash_completion.sh
            fi
        fi

        if [[ -r "/c/volla/metadata-config.bash" ]]; then
            # shellcheck disable=SC1090,SC1091
            source "/c/volla/metadata-config.bash"
        elif [[ -r "/p/pwa/\${USER}/${_VOLLA_HOME_FOLDER}/metadata-config.bash" ]]; then
            # shellcheck disable=SC1090,SC1091
            source "/p/pwa/\${USER}/${_VOLLA_HOME_FOLDER}/metadata-config.bash"
        fi

        if [[ -r "\${HOME}/.modules.user" ]]; then
            # In below sourced file (.modules.user) you can place the
            # module add commands for the modules you want to have
            # loaded in each Bash instance (depending on what is
            # included or not included in your SECI), for instance
            #
            # module add git/2.23.0-2
            # module add git-completion/2.23.0-2
            #
            # Note that the version of git-completion MUST match the
            # loaded version of git!
            #
            # shellcheck disable=SC1090,SC1091
            source "\${HOME}/.modules.user"
        fi

        # Optional line; either comment with '#' character or remove
        # line altogether if you do not want this (Bash shell prompt
        # that show Git status among other things)
        source /p/avionics-tools/opt/liquidprompt/liquidprompt
        ;;
    MINGW*)
        # Git Bash already comes with pre-configured Bash completion
        # support as well as Git completion support.
        if [[ -r "/c/volla/metadata-config.bash" ]]; then
            # shellcheck disable=SC1091
            source "/c/volla/metadata-config.bash"
        elif [[ -r "/x/${_VOLLA_HOME_FOLDER}/metadata-config.bash" ]]; then
            # shellcheck disable=SC1091
            source "/x/${_VOLLA_HOME_FOLDER}/metadata-config.bash"
        fi
        ;;
esac
# Frija initialization end
##########################

EOF

    print_separator "8< Cut Here (end of script snippet to include in .bash_profile) 8<" "${BOLD}"
}


function print_init_message()
{
    cat <<EOF

${BOLD}FRIJA AND VOLLA INITIALIZATION INSTRUCTIONS${CLEAR}
${BOLD}===========================================${CLEAR}

${BOLD}Manual Initialization${CLEAR}
${BOLD}---------------------${CLEAR}
To manually acativate Frija each time a new shell is started you have to
explicitly source the file ${BOLD}${_VOLLA_PATH}/${configFileName}${CLEAR}
by executing the command below from the Bash command line
  ${BOLD}source ${_VOLLA_PATH}/${configFileName}${CLEAR}


${BOLD}Automatic Initialization${CLEAR}
${BOLD}------------------------${CLEAR}
To automatically activate Frija each time a new shell is started you have to
add a script snippet to your init file ${BOLD}${HOME:?}/.bash_profile${CLEAR}.

Please re-run ${BOLD}${_FRIJA_PROGRAM_NAME}${CLEAR} with option -c/--code to show this code snippet, e.g.
  ${BOLD}${BOOTSTRAP_RELATIVE_PATH} --code${CLEAR}

EOF

    print_separator ""
    case "${OPERATING_SYSTEM}" in
        "${WINDOWS_OS}")
            cat <<EOF
${BOLD}Windows users${CLEAR}, PLEASE re-run ${BOLD}${_FRIJA_PROGRAM_NAME}${CLEAR} with -w/--windows option for further
information, e.g.
  ${BOLD}${BOOTSTRAP_RELATIVE_PATH} --windows${CLEAR}

EOF
            ;;
        "${LINUX_OS}")
            ;;
    esac

    cat <<EOF
${BOLD}To test${CLEAR} installation try command 'frija --help' and if you get a friendly help
message you are done!

${BOLD}Once you have${CLEAR} verified that the command works, the next step is to use the
frija init subcommand.
EOF
    print_separator ""
    cat <<EOF

${BOLD}Note:${CLEAR} TAB completion should also work for ${UNDERLINE_ON}all${UNDERLINE_OFF} frija commands!
${BOLD}Note:${CLEAR} All frija commands support -h/--help option.

EOF
}


function print_windows_init_message()
{
    cat <<EOF

${BOLD}FRIJA AND VOLLA WINDOWS CONFIGURATION TIP${CLEAR}
${BOLD}=========================================${CLEAR}
To change the look-and-feel of the MinTTY terminal Git Bash uses you can use a
${BOLD}.minttyrc${CLEAR} configuration text file placed in your home folder.

An example ${BOLD}.minttyrc${CLEAR} file is placed in the root of the ${BOLD}${_REPO_NAME}${CLEAR} repo,
i.e.
  ${BOLD}cp ${_VOLLA_PATH}/${_REPO_NAME}/.minttyrc ${HOME}${CLEAR}

If you do this, the next time MinTTY is started it will use the configuration
file ${BOLD}${HOME}.minttyrc${CLEAR} (this is where the settings are stored).

${BOLD}Note:${CLEAR} The example configuration file enables the same copy and paste shortcuts
      as Gnome Terminal uses; Shift+Crtl-C to copy and Shift+Ctrl-V to paste.
      It also turns off cursor blink and enables block cursor.

      Since it is a plain-text file you can modify it to your liking (some of
      the options, but not all, can be set from within MinTTY option dialog.

${BOLD}Note:${CLEAR} Some settings does not seem to work via GUI (like changing or creating
      color palettes). These settings must thus be done via the text
      configuration file.

EOF
}


function print_linux_init_message()
{
    cat <<EOF

${BOLD}FRIJA AND VOLLA LINUX CONFIGURATION TIP${CLEAR}
${BOLD}=======================================${CLEAR}
As of now there are no additional configuration steps for Linux users. :)

EOF
}


# Iterate over options in order and nicely split until we see --
while true; do
    case "${1}" in
        -i|--instructions)
            # Print init message and exit
            initMessage="y"
            shift  # Move to next option
            ;;
        -c|--code)
            # Show .bash_profile init code
            print_init_code
            exit 0
            ;;
        -w|--windows)
            print_windows_init_message
            exit 0
            ;;
        -l|--linux)
            print_linux_init_message
            exit 0
            ;;
        -v|--verbose)
            ensure_boolean_option_not_set "Verbose" "${VERBOSE}"
            VERBOSE="y"
            shift  # Move to next option
            ;;
        -h|--help)
            _frija_subcommand_usage
            exit 0
            ;;
        -d|--debug)
            ensure_boolean_option_not_set "Debug" "${DEBUG}"
            DEBUG="y"
            shift
            ;;
        -D|--dry-run)
            # See .core_preamble.bash for more information
            set_dry_run
            shift
            ;;
        -f|--force-os)
            ensure_option_not_set "OS override" "${osOverride}"
            shift  # Move to next option
            osOverride="${1}"
            ensure_option_argument_set "OS override" "${osOverride}"
            shift  # Move to next option
            ;;
        --)
            shift
            break
            ;;
        *)
            print_error "Internal command line parsing error; Current option is '${1}' and rest is '${*}'" 3
            ;;
    esac
done


# Allow user to explicitly override detected OS
if [[ -n "${osOverride}" ]]; then
    OPERATING_SYSTEM="${osOverride}"
fi

print_debug "DEBUG='${DEBUG}'"
print_debug "OPERATING_SYSTEM='${OPERATING_SYSTEM}'"

BOOTSTRAP_RELATIVE_PATH=$(relative_executable_path "${_FRIJA_PROGRAM_PATH}")

if [[ -n "${initMessage}" ]]; then
    print_init_message
    exit 0
fi


print_debug "verbose='${VERBOSE}', debug='${DEBUG}', dry_run='${DRY_RUN}'"

if [[ -d "${_VOLLA_PATH}/${_REPO_NAME}" ]]; then
    print_error "Metadata tools is already installed in '${BOLD}${_VOLLA_PATH}/${_REPO_NAME}${CLEAR}'. Please either run '${BOLD}${_FRIJA_USAGE_NAME} --instructions${CLEAR}' or remove '${BOLD}${_VOLLA_PATH}${CLEAR}' folder and try again." 7
fi


print_message ""
print_message "Setting up bootstrap environment..."

declare -a command
command=("${SINGLE}" "Create dummy volla folder structure" \
                     mkdir --parents "${_VOLLA_PATH}/${_REPO_NAME}/bin")
run "${command[@]}"

# Dummy file needed so we can source metadata-config.bash (it sources
# this file which is needed for TAB-completion which we will not need
# right now as we are not interactive on the command line).
command=("${SINGLE}" "Create dummy frija file" \
                     touch "${_VOLLA_PATH}/${_REPO_NAME}/bin/frija")
run "${command[@]}"

INHIBIT_NOT_FOUND_MESSAGE="y"
# shellcheck source=./config/metadata-config.bash
source "${_REPO_PATH}/config/metadata-config.bash"

# Override definition of METADATATOOLS_HOME variable so it points to
# the temporary location of the metadata_tools repo.
METADATATOOLS_HOME="${_REPO_PATH}/bin"


print_message ""
print_message "Now we can create the real environment..."

print_debug "_VOLLA_PATH='${_VOLLA_PATH}"
print_debug "_REPO_NAME='${_REPO_NAME}"
print_debug "Command: '${_VOLLA_PATH}/${_REPO_NAME:?}'"
# Ensure _REPO_NAME never ends with '/' by using :? for expansion
# Remove the dummy structure we created above to get scripts
# source-able (yes, the sourced scripts are tricked to believe there
# is something installed in the correct place)
command=("${LAST}" "Remove dummy volla folder structure" rm -fr "${_VOLLA_PATH}/${_REPO_NAME:?}")
run "${command[@]}"


# Base path is the search path to the metadata tools repo containing
# this command. That is the name of the command is removed and the
# folder containing the command from the path. What remains is the
# _VOLLA_BASE_PATH.
#
# Remove shortest suffix matching "/*/*", i.e. last and 2nd last part of path
_VOLLA_BASE_PATH="${METADATATOOLS_HOME%/*}"


command=("${FIRST}" "Initialize volla file structure" \
                    mkdir --parents "${_VOLLA_PATH}")
run "${command[@]}"


# Finally filter config file so $searchString below is assigned the
# name of the metadata tools repo. This is done using sed.
searchString="export METADATATOOLS_REPONAME"

# sed expression to replace all occurrences of $searchString with $_REPO_NAME
sedExpression="s/${searchString}=''/${searchString}=\"${_REPO_NAME}\"/"

# File to filter using sed
inputFilePath="${configFile[0]}"

# File to store sed result in; remove longest matching prefix "*/"
# from $inputFile, i.e. all path components up to but not including
# the file name itself.
outputFilePath="${_VOLLA_PATH}/${inputFilePath##*/}"

# sed command to execute where output of command is redirected to
# $outputFilePath
command=("${LAST}" "Initialize volla file structure" "${outputFilePath}" \
                   sed -e "${sedExpression}" "${inputFilePath}")
run_with_redirect "${command[@]}"


command=("${SINGLE}" "Copy metadatatools repo to Volla folder" \
                     cp -r "${_VOLLA_BASE_PATH}" "${_VOLLA_PATH}")
run "${command[@]}"


print_message ""
print_message "${BOLD}Frija${CLEAR} and ${BOLD}Volla${CLEAR} metadata tools successfully installed!${CLEAR}"
print_message ""
print_message "For initialization instructions, please re-run ${BOLD}${_FRIJA_PROGRAM_NAME}${CLEAR} with -i/--instructions option, e.g."
print_message "  ${BOLD}${BOOTSTRAP_RELATIVE_PATH} --instructions${CLEAR}"
print_message ""
print_message ""
print_separator
print_message "Once ${BOLD}Frija${CLEAR} and ${BOLD}Volla${CLEAR} have been initialized properly, the next step is to run command"
print_message "  ${BOLD}frija locale --help${CLEAR}"
print_message "and follow the onscreen instructions. :)"
print_separator
print_message ""
