################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################
#
# DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN WHEN FRIJA IS
# UPDATED OR (RE)INSTALLED
#
# Check what system we are running on. Fensalir support scripts and
# functions may depend on these variables being properly initialized.
#
# Please do not remove.
# _unameOut="$(uname -s)"
#
# # Fensalir setup script and provided Bash support scripts depend on
# # these variables being properly initialized and exported
# export _FENSALIR_CURRENT_OS=""
# export _FENSALIR_SOLARIS="Solaris"
# export _FENSALIR_LINUX="Linux"
# export _FENSALIR_WINDOWS="Windows"
#
# case "${_unameOut}" in
#     SunOS)
#         _FENSALIR_CURRENT_OS="${_FENSALIR_SOLARIS}"
#         ;;
#     Linux*)
#         _FENSALIR_CURRENT_OS="${_FENSALIR_LINUX}"
#         ;;
#     MINGW*)
#         _FENSALIR_CURRENT_OS="${_FENSALIR_WINDOWS}"
#         ;;
#     *)
#         echo "Unknown OS '${_unameOut}'" 1>&2
#         return
#         ;;
# esac
#
# # Ensure $XDG_CONFIG_HOME is set
# XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
# FENSALIR_USER_CONFIG_HOME="${XDG_CONFIG_HOME}/Fensalir"
#
# # Note that sourced script depends on $FENSALIR_USER_CONFIG_HOME
# # is configured as above
# #
# # shellcheck source=.config/Fensalir/bashrc.bash
# source "${FENSALIR_USER_CONFIG_HOME}/bashrc.bash"
#
################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################


################################################################################
# Start of configuration settings
################################################################################

## By leaving configuration option below as a commented line you get
## English US UTF-8 as the configured locale. This is usually the
## default in Linux and you might get "funny" behavior in for instance
## Solaris when writing non US ASCII characters in the terminal if you
## opt out of this.
##
## Enable OS-dependent locale by uncommenting line below
#_FENSALIR_UTF8_SUPPORT="No"

## Enable OS-dependent pager (for instance manual page pager) instead
## of explicitly setting it to less by uncommenting line below
#_FENSALIR_LESS_AS_PAGER="No"

## Enable OS-dependent less color support instead of explicitly
## activating it by uncommenting line below
#_FENSALIR_LESS_AS_PAGER="No"

## Enable Solaris grep as 'grep' command instead of an alias 'grep'
## for 'ggrep' (GNU grep) by uncommenting line below
#_FENSALIR_SOLARIS_ALIAS_GNU_GREP

## By leaving configuration option below as a commented line you get
## color support in GNU grep for marking the match on the reported
## line as well as automatic exclusion of files within the .git
## folder.
##
## Enable OS-dependent GNU grep configuration by uncommenting line below
#_FENSALIR_SOLARIS_ALIAS_GNU_GREP

## Disable Git completion support by uncommenting line below
#_FENSALIR_GIT_COMPLETION="No"

## Enable OS-default Git pager instead of less by uncommenting line
## below
#_FENSALIR_GIT_PAGER="No"

## Fensalir Git-prompt
## -------------------
## Color of shell-prompt changes when inside a Git repo depending on
## state of Git repo. When repo is dirty compact short-diff is added
## to prompt within parentheses with fields separated by slash; order
## is number of added files, number of modified files, number of added
## lines, and number of deleted lines.
##
## Disable Git-prompt by uncommenting line below
#_FENSALIR_GIT_PROMPT="No"

## Set Frija help pager to 'cat' instead of configured default pager
## by uncommenting line below. Note that you may also configure this
## explicitly by setting the environment variable FRIJAPAGER to the
## command to use as the Frija help pager.
# _FRIJA_DEFAULT_PAGER="No"

################################################################################
# End of configuration settings
################################################################################


if [[ -d "${FENSALIR_USER_CONFIG_HOME}" ]]; then
    # On Solaris Bash 5 is used instead of Bash 3. Fensalir requires
    # Bash 4.2 or newer. This script will also configure Bash to
    # remove duplicate entries in its history (for instance what you
    # get when pressing up/down arrows), tells Bash to append to the
    # history file instead of overwriting it, turn on support for
    # extended globbing, and ensuring that programmable completion is
    # enabled (it is enabled by default).
    #
    # Note that a function called 'expunge' is also defined. This
    # function will recursively remove all Emacs backup and auto-save
    # files. If no argument is given the search starts in the current
    # directory. Optionally a path may be given as the first argument
    # and then the search starts in that directory.
    #
    # Also configures some aspects of Bash CLI
    # environment depending on configuration options above.
    FENSALIR_BASH="${FENSALIR_USER_CONFIG_HOME}/fensalir-bash-setup.bash"
    if [[ -r "${FENSALIR_BASH}" ]]; then
        # shellcheck source=./fensalir-bash-setup.bash
        source "${FENSALIR_BASH}"
    fi

    # Activate latest installed version of Git. Fensalir may depend on
    # features available in latest version of Git. Also configures
    # some aspects of Git experience when using the CLI depending on
    # configuration options above.
    FENSALIR_GIT="${FENSALIR_USER_CONFIG_HOME}/fensalir-git-setup.bash"
    if [[ -r "${FENSALIR_GIT}" ]]; then
        # shellcheck source=./fensalir-git-setup.bash
        source "${FENSALIR_GIT}"
    fi

    # Find out if Fensalir is installed, if so activate it. Comment
    # out or remove if you have uninstalled Fensalir.
    FENSALIR_ACTIVATE="${FENSALIR_USER_CONFIG_HOME}/fensalir-activate.bash"
    if [[ -r "${FENSALIR_ACTIVATE}" ]]; then
        # shellcheck source=./fensalir-activate.bash
       source "${FENSALIR_ACTIVATE}"
    fi
fi
