// C-wrapper for starting an Ada executable built directly using GCC.
//
// Assuming there is a file called fnord_main.adb which contain
// something like
//
// procedure Fnord_Main is
// begin
// ...
// end Fnord_Main;
//
// Then when gnatbind is called from the Makefile the option '-L' is used
// which implies '-n' that in turn causes "no Ada main program (forign
// main routine)" which this file provide.
//
// The main() function in this file need to explicitly call the main
// function corresponding to Fnord_Main above. Due to that Ada is case
// insensitive in combination with how the Makefile invokes gnatbind
// the actual function name that the main() function should call is
// transformed to _ada_fnord_main().
//
// PLEASE NOTE that before this function, _ada_fnord_main() (you have
// to replace this with whatever is used in the ADN file), can be
// called the Ada environment generated by gnatbind must be
// initialized and after the _ada_fnord_main() function exits the
// environment must be finalized. The names of the init and
// finalization functions are implicitly defined via the '-L' option
// to gnatbind.
//
// The Makefile in turn uses $FRIJA_ID combined with name of the
// executable for the initialization and finalization functions to
// "guarantee" that the names are unique and not conflicting with any
// symbols found in the source code for the executable and thus their
// names can't be hard-coded.
//
// The header file 'frija_cmain.h' in turn defines the FRIJA_ADA_INIT
// and FRIJA_ADA_FINAL macros used by this file by using a macro
// called FRIJA_ADA_MAIN. This FRIJA_ADA_MAIN macro is automatically
// defined by the Makefile on the GCC command line when building an
// executable folder that contain this C source file.
#include "frija_cmain.h"

extern void FRIJA_ADA_INIT(void);
// Replace 'fnord_main' below with whatever is used in the ADB file
// and remove this comment.
extern void _ada_fnord_main(void);
extern void FRIJA_ADA_FINAL(void);

int main(int argc, char **argv)
{
  (void)(argc);
  (void)(argv);

  FRIJA_ADA_INIT();
  // Replace 'fnord_main' below with whatever is used in the ADB file
  // and remove this comment.
  _ada_fnord_main();
  FRIJA_ADA_FINAL();

  return 0;
}
