// C-wrapper for starting an Ada executable built directly using GCC.
//
// When gnatbind is called from the Makefile the option '-L' is used
// which implies '-n' that in turn causes "no Ada main program (forign
// main routine)" which this file provide. Before _ada_main() function
// can be called the Ada environment generated by gnatbind must be
// initialized and after the _ada_main() function exits the
// environment must be finalized. The names of the init and
// finalization functions are implicitly defined via the '-L' option
// to gnatbind.
//
// The Makefile in turn uses $FRIJA_ID combined with name of the
// executable for this and thus it can't be hard-coded. The header
// file 'frija_cmain.h' in turn defines the FRIJA_ADA_INIT and
// FRIJA_ADA_FINAL macros used by this file by using a macro called
// FRIJA_ADA_MAIN. This FRIJA_ADA_MAIN macro is automatically defined
// by the Makefile on the GCC command line when building an executable
// folder that contain this C source file.
#include "frija_cmain.h"

extern void FRIJA_ADA_INIT(void);
extern void _ada_main(void);
extern void FRIJA_ADA_FINAL(void);

int main(int argc, char **argv)
{
  (void)(argc);
  (void)(argv);

  FRIJA_ADA_INIT();
  _ada_main();
  FRIJA_ADA_FINAL();

  return 0;
}
