################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################
#
# DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN WHEN FRIJA IS
# UPDATED OR (RE)INSTALLED
#
################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################


# Check what system we are running on. Fensalir support scripts and
# functions may depend on these variables being properly initialized.
_unameOut="$(uname -s)"

# Fensalir setup script and provided Bash support scripts depend on
# these variables being properly initialized and exported
export _FENSALIR_SOLARIS="Solaris"
export _FENSALIR_LINUX="Linux"
export _FENSALIR_WINDOWS="Windows"

_FENSALIR_SOLARIS_VERSION=""
_FENSALIR_CURRENT_OS=""

case "${_unameOut}" in
    SunOS)
        _FENSALIR_CURRENT_OS="${_FENSALIR_SOLARIS}"
        _FENSALIR_SOLARIS_VERSION="$(uname -r)"
        # Strip leading digit to go from SunOS version to Solaris
        # version, e.g. "5.10" --> "10"
        _FENSALIR_SOLARIS_VERSION="${_FENSALIR_SOLARIS_VERSION#*.}"
        ;;
    Linux*)
        _FENSALIR_CURRENT_OS="${_FENSALIR_LINUX}"
        ;;
    MINGW*)
        _FENSALIR_CURRENT_OS="${_FENSALIR_WINDOWS}"
        ;;
    *)
        echo "Unknown OS '${_unameOut}'" 1>&2
        return
        ;;
esac

export _FENSALIR_SOLARIS_VERSION
export _FENSALIR_CURRENT_OS
