################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################
# DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN WHEN FRIJA IS
# UPDATED OR (RE)INSTALLED
#
# This file script depend on the following variables being properly initialized
#
# _FENSALIR_CURRENT_OS
# _FENSALIR_SOLARIS
# _FENSALIR_LINUX
# _FENSALIR_WINDOWS
#
# before it is sourced.
#
#
# Furthermore, it also depend on the following opt-out variables that
# dictate behavior of the Git configuration. If any of them is set to
# a non-empty string then it inhibits the respective configuration.
#
# _FENSALIR_GIT_COMPLETION
# _FENSALIR_GIT_PAGER
# _FENSALIR_GIT_PROMPT
################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################


if [[ -n "${_FENSALIR_CURRENT_OS}" ]] \
       && [[ "${_FENSALIR_CURRENT_OS}" != "${_FENSALIR_WINDOWS}" ]]
then
    if [[ -r "${HOME}/.modules.user" ]]; then
        if grep --quiet \
                --extended-regexp \
                --regexp="^[^#]*module .* git(-.*)?(/.*)?$" \
                "${HOME}/.modules.user";
        then
            # File $HOME/.modules.user contain at least one module
            # command involving Git, print a warning message about
            # this to stderr using a here-document
            cat 1>&2 <<EOF

--------------------------------------------------------------------------------
WARNING: If file ~/.modules.user is sourced then it will explicitly load
         at least one git module which might be in conflict with the DEFAULT
         (latest available version) git module loaded by this init file
            '${BASH_SOURCE[0]}'

         Please either remove or comment out those lines.
--------------------------------------------------------------------------------

EOF
        fi
    fi
fi



if [[ -z "${_FENSALIR_GIT_PROMPT}" ]] \
       || [[ "${_FENSALIR_GIT_PROMPT,,}" == "y" ]] \
       || [[ "${_FENSALIR_GIT_PROMPT,,}" == "yes" ]]; then
    # Enable expansion of prompt before it is shown. This means that the
    # function _frija_git_bash_prompt() will be called and its output
    # inserted into the prompt string.
    shopt -s promptvars

    _FENSALIR_PESC=$(echo -e "\\e")
    _FENSALIR_PCLEAR=$(tput sgr0)
    _FENSALIR_PBOLD=$(tput bold)

    # Escape sequence returned by tput command must be protected
    # by wrapping them within '\[' and '\]'; double '\' needed to
    # avoid that Bash consumes the '\'.
    _FENSALIR_PCLEAR="\\[${_FENSALIR_PCLEAR}\\]"
    _FENSALIR_PBOLD="\\[${_FENSALIR_PBOLD}\\]"
fi

# Poor man implementation of liquid prompt that provide Git-related
# information in the prompt. Only used when variable
# _FENSALIR_GIT_PROMPT is unset or set to the empty string.
function _fensalir_git_bash_prompt()
{
    local gitStatus=""
    local prompt=""
    local branch=""
    local detachedHead=""
    gitStatus=$(git rev-parse --is-inside-work-tree 2>&1)
    if [[ "${gitStatus}" == "true" ]]; then
        if branch="$(git symbolic-ref -q HEAD)"; then
            # Remove prefix "refs/heads/" from returned
            # string
            branch="${branch#refs/heads/}"
        else
            # Repo is in detached head state, use commit
            # SHA instead
            branch=$(git rev-parse --short -q HEAD)
            branch="${branch}"
            detachedHead=" (Detached HEAD)"
        fi

        # VT100 "red" (31), "yellow" (33), "blue" (34), "green" (32),
        # and "magenta" (35) indices (actual color set in terminal)
        # used for changes, unpushed commits, up-to-date state, as
        # well as short stats.
        #
        # NOTE: ALL escape sequences used in a prompt MUST be
        # protected with enclosing \\[ and \\]
        local CHANGES="\\[${_FENSALIR_PESC}[31m\\]"
        local COMMITS_AHEAD="\\[${_FENSALIR_PESC}[33m\\]"
        local COMMITS_BEHIND="\\[${_FENSALIR_PESC}[34m\\]"
        local UPTODATE="\\[${_FENSALIR_PESC}[32m\\]"
        local DIFF="\\[${_FENSALIR_PESC}[35m\\]"

        local end="${_FENSALIR_PCLEAR}"
        if git status --porcelain 2>/dev/null | grep -Eq '^\\?\\?'; then
            end="${CHANGES}*${end}"
        fi

        # If there are stashed items it supersedes the marking at the
        # end of the prompt
        if [[ -n "$(git stash list -n 1  2>/dev/null)" ]]; then
            end="${COMMITS_AHEAD}+${end}"
        fi

        local remote=""
        remote=$(git config \
                     --get branch."${branch}".remote \
                     2>/dev/null)
        declare -i commitsAhead=0
        declare -i commitsBehind=0
        if [[ -n "${remote}" ]]; then
            local rBranch=""
            rBranch=$(git config --get branch."${branch}".merge)
            if [[ -n "${rBranch}" ]]; then
                commitsAhead=$(git rev-list \
                              --count "@{upstream}..HEAD" \
                              2>/dev/null)
                if [[ -z "${commitsAhead}" ]]; then
                    commitsAhead=0
                fi

                commitsBehind=$(git rev-list \
                              --count "HEAD..@{upstream}" \
                              2>/dev/null)
                if [[ -z "${commitsBehind}" ]]; then
                    commitsBehind=0
                fi
            fi
        fi

        local shortstat=""
        # Changes in working tree since last commit; what would be
        # committed if you run "git commit -a", that is stage all
        # changes to tracked files
        shortstat=$(git diff --shortstat HEAD  2>/dev/null)
        if [[ -n "${shortstat}" ]]; then
            # Changes in working tree not yet staged for the next commit
            local unstaged=""
            unstaged=$(git diff --shortstat  2>/dev/null)

            local regex="^[^0-9]*(([0-9]+) files? changed, )?"
            regex+="(([0-9]+) insertions..., )?"
            regex+="(([0-9]+) deletions...)?.*$"

            declare -i added=0

            if [[ "${shortstat}" =~ $regex ]]; then
                # Total number of files added to index
                added="${BASH_REMATCH[2]:-0}"
            fi

            if [[ "${unstaged}" =~ $regex ]]; then
                declare -i files="${BASH_REMATCH[2]:-0}"
                declare -i inserts="${BASH_REMATCH[4]:-0}"
                declare -i deletes="${BASH_REMATCH[6]:-0}"

                shortstat="${added}/${files}/"

                if (( inserts > 0 )); then
                    shortstat+="+${inserts}/"
                else
                    shortstat+="0/"
                fi

                if (( deletes > 0 )); then
                    shortstat+="-${deletes}"
                else
                    shortstat+="0"
                fi

                prompt="${CHANGES}${branch}${_FENSALIR_PCLEAR}"

                prompt+="(${DIFF}${shortstat}"
                if (( commitsAhead > 0 )) && (( commitsBehind > 0 )); then
                    prompt+=",${COMMITS_AHEAD}A${commitsAhead}-"
                    prompt+="${COMMITS_BEHIND}B${commitsBehind}"
                elif  (( commitsAhead > 0 )); then
                    prompt+=",${COMMITS_AHEAD}A${commitsAhead}"
                elif (( commitsBehind > 0 )); then
                    prompt+=",${COMMITS_BEHIND}B${commitsBehind}"
                fi
                prompt+="${_FENSALIR_PCLEAR})"
            fi
        else
            # No delta compared to last commit, but there might be
            # non-pushed commitsAhead and if so indicate that
            if (( commitsAhead > 0 )) && (( commitsBehind > 0 )); then
                prompt="${DIFF}${branch}${_FENSALIR_PCLEAR}"
                prompt+="(${COMMITS_AHEAD}A${commitsAhead}-"
                prompt+="${COMMITS_BEHIND}B${commitsBehind}"
                prompt+="${_FENSALIR_PCLEAR})"
            elif (( commitsAhead > 0 )); then
                prompt="${COMMITS_AHEAD}${branch}${_FENSALIR_PCLEAR}"
                prompt+="(${COMMITS_AHEAD}A${commitsAhead}"
                prompt+="${_FENSALIR_PCLEAR})"
            elif (( commitsBehind > 0 )); then
                prompt="${COMMITS_BEHIND}${branch}${_FENSALIR_PCLEAR}"
                prompt+="(${COMMITS_BEHIND}B${commitsBehind}"
                prompt+="${_FENSALIR_PCLEAR})"
            else
                prompt="${UPTODATE}${branch}${_FENSALIR_PCLEAR}"
            fi
        fi
        prompt+="${end}${detachedHead} "
    fi

    prompt+="${_FENSALIR_PBOLD}"'$'"${_FENSALIR_PCLEAR}"

    # VT100 "magenta" (35) and "blue" (34) indices are used for
    # highlighting user and hostname respectively. Path is marked
    # using plain bold.
    #
    # NOTE: ALL escape sequences used in a prompt MUST be protected
    # with enclosing \\[ and \\]
    local userColor="\\[${_FENSALIR_PESC}[35m\\]"
    local hostColor="\\[${_FENSALIR_PESC}[34m\\]"
    local pathColor="${_FENSALIR_PBOLD}"
    # Set prompt, otherwise we get Bash default prompt
    PS1="[${userColor}\\u${_FENSALIR_PCLEAR}@"
    PS1+="${hostColor}\\h${_FENSALIR_PCLEAR}:"
    PS1+="${pathColor}\\w${_FENSALIR_PCLEAR}]\\n"
    PS1+=" ${prompt} "
}


if [[ "${_FENSALIR_CURRENT_OS}" == "${_FENSALIR_SOLARIS}" ]] \
       || [[ "${_FENSALIR_CURRENT_OS}" == "${_FENSALIR_LINUX}" ]]
then
    if [[ "${PWD}" =~ ^/p/pwa-user/[^/]+/(.*)$ ]]; then
        # Change from /p/pwa-user/<number>/... to /p/pwa/... which
        # is the "official" PWA path. The other is the actual
        # location of the PWA folder for the user which is then
        # mapped as the more generic one. Alas when creating tabs
        # in Terminal application when current working directory
        # is within PWA folder you get the actual path and not the
        # official one.
        #
        # shellcheck disable=SC2164
        cd "/p/pwa/${BASH_REMATCH[1]}"
    fi

    # Ensure default Git is available, should be latest version
    module --silent add git
    if [[ -z "${_FENSALIR_GIT_COMPLETION:-}" ]] \
	   || [[ "${_FENSALIR_GIT_COMPLETION,,}" == "y" ]] \
	   || [[ "${_FENSALIR_GIT_COMPLETION,,}" == "yes" ]]; then
       module --silent add git-completion

       if [[ -n "${SAAB_GIT_COMPLETIONS}" ]]; then
	   if [[ -r "${SAAB_GIT_COMPLETIONS}" ]]; then
               # Source script enabling Git completions
               #
               # shellcheck disable=SC1090
               source "${SAAB_GIT_COMPLETIONS}"
           else
               echo "ERROR: Git completion not available;" \
                    "sourcing of '${SAAB_GIT_COMPLETIONS}' failed" \
                    "for some reason." 1>&2
           fi
       fi
    fi
fi

if [[ "${_FENSALIR_CURRENT_OS}" == "${_FENSALIR_SOLARIS}" ]] \
       || [[ "${_FENSALIR_CURRENT_OS}" == "${_FENSALIR_LINUX}" ]] \
       || [[ "${_FENSALIR_CURRENT_OS}" == "${_FENSALIR_WINDOWS}" ]]
then

    if [[ -z "${_FENSALIR_GIT_PAGER}" ]]; then
        export GIT_PAGER="less --quit-if-one-screen"
    fi

    if [[ -z "${_FENSALIR_GIT_PROMPT}" ]]; then
        # The function/command name stored in $PROMPT_COMMAND is
        # executed before a prompt is shown. In this way the prompt
        # can be made to adapt after current conditions, like if CWD
        # is within a Git-repo or not.
        PROMPT_COMMAND=_fensalir_git_bash_prompt
    fi
fi
