################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################
# DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN WHEN FRIJA IS
# UPDATED OR (RE)INSTALLED
#
# This file script depend on the following variables being properly initialized
#
# _FENSALIR_CURRENT_OS
# _FENSALIR_SOLARIS
# _FENSALIR_LINUX
# _FENSALIR_WINDOWS
#
# before it is sourced.
#
#
# Furthermore, it also depend on the following opt-out variables that
# dictate behavior of the Git configuration. If any of them is set to
# a non-empty string then it inhibits the respective configuration.
#
# _FRIJA_DEFAULT_PAGER
################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################

# Temporary function for printing message about Fensalir not being
# installed.
#
# Function is removed at end of script
function _frija_print_not_installed()
{
    local installationPath="${1:-}"

    local message="Note: Fensalir not installed"

    if [[ "${fullclone:-}" == "true" ]]; then
        message="Windows FC (full clone) machine: ${message} "
    fi

    if [[ -n "${installationPath}" ]]; then
        message+="at '${installationPath}'"
    fi

    # Write message to standard error.
    echo "${message}; it is not available in your environment." 1>&2
}


_FENSALIR_GREP="grep"
export _FENSALIR_GREP

# Temporary variable that contain OS-dependent search path to expected
# Frija installation
fensalirPath=""
fensalirNotInstalledPath=""

case "${_FENSALIR_CURRENT_OS}" in
    ${_FENSALIR_SOLARIS})
        #echo "Solaris system detected"

        # Ensure GNU Grep is called from Fensalir scripts
        _FENSALIR_GREP='ggrep'
        export _FENSALIR_GREP
        ;&  # Fall-through to next list
    ${_FENSALIR_LINUX})
        #echo "Linux system detected"

        fensalirPath="/p/pwa/${USER}/volla/fensalir-setup.bash"
        fensalirNotInstalledPath="/p/pwa/${USER}"
        ;;
    ${_FENSALIR_WINDOWS})
        #echo "Windows system detected"

        if [[ "${fullclone:-}" == "true" ]]; then
            fensalirPath="/c/volla/fensalir-setup.bash"
            fensalirNotInstalledPath="C:\\"
        else
            fensalirPath="/x/volla/fensalir-setup.bash"
            fensalirNotInstalledPath="X:\\ (PWA)"
        fi
        ;;
    *)
        fensalirNotInstalledPath="${OS_PWA:-Unknown OS}"
        ;;
esac

if [[ -n "${fensalirPath}" ]]; then
    if [[ -r "${fensalirPath}" ]]; then
        if [[ -z "${_FRIJA_DEFAULT_PAGER:-}" ]]; then
            FRIJAPAGER="cat"
            export FRIJAPAGER
        fi

        echo "Sourcing '${fensalirPath}'" 1>&2

        # Shellcheck path below is relative to Fensalir repo path.
        # Hence if your personal copy that is outside of this repo
        # then Shellcheck will complain. This is as it is since it is
        # not possible to silence Shellcheck in both cases.
        #
        # shellcheck source=../../fensalir-setup.bash
        source "${fensalirPath}"
    else
        _frija_print_not_installed "${fensalirNotInstalledPath}"
    fi
fi

# Remove temporary variables from environment
unset fensalirPath
unset fensalirNotInstalledPath

# Remove function _frija_print_not_installed from environment
unset -f _frija_print_not_installed
