################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################
#
# DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN WHEN FRIJA IS
# UPDATED OR (RE)INSTALLED
#
################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################


# Check what system we are running on. Fensalir support scripts and
# functions may depend on these variables being properly initialized.
_unameOut="$(uname -s)"

# Fensalir init script and provided Bash support scripts depend on
# these constant variables being properly initialized and exported
declare -r -x _FENSALIR_LINUX="Linux"

# Array of supported operating systems
declare -a -x _FENSALIR_SUPPORTED_OS_ARRAY=( "${_FENSALIR_LINUX}"
					     )

# Currently used operating system
_FENSALIR_CURRENT_OS=""

# Currently used operating system version; with OS-specific variable
# name. Note: These variables might be assigned empty values.
_FENSALIR_LINUX_VERSION=""

# Currently used operating system version; with OS-generic variable
# name. Note: This variable might be assigned an empty value.
_FENSALIR_OS_VERSION=""


case "${_unameOut}" in
    Linux*)
        _FENSALIR_CURRENT_OS="${_FENSALIR_LINUX}"
        _FENSALIR_LINUX_VERSION=""
        _FENSALIR_OS_VERSION="${_FENSALIR_LINUX_VERSION}"
        ;;
    *)
        echo "Unknown OS '${_unameOut}'" 1>&2
        return
        ;;
esac

export _FENSALIR_LINUX_VERSION

export _FENSALIR_OS_VERSION
export _FENSALIR_CURRENT_OS

declare -a _FENSALIR_SUPPORTED_OS_VARIANTS=( "${_FENSALIR_LINUX}" \
                                             )
export _FENSALIR_SUPPORTED_OS_VARIANTS

_FENSALIR_OS_ID="${_FENSALIR_CURRENT_OS}${_FENSALIR_OS_VERSION}"
export _FENSALIR_OS_ID
