################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################
# DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN WHEN FRIJA IS
# UPDATED OR (RE)INSTALLED
#
# This file script depend on the following variables being properly initialized
#
# _FENSALIR_CURRENT_OS
# _FENSALIR_LINUX
#
# before it is sourced.
#
#
# Furthermore, it also depend on the following opt-out variables that
# dictate behavior of the Git configuration. If any of them is set to
# a non-empty string then it inhibits the respective configuration.
#
# _FENSALIR_UTF8_SUPPORT
# _FENSALIR_LESS_AS_PAGER
# _FENSALIR_LESS_COLOR
# _FENSALIR_COLOR_GNU_GREP
################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################

HISTCONTROL=ignoredups:erasedups  # No duplicate entries in history

shopt -s checkwinsize;  # resize bash window when processes exit
shopt -s histappend;    # append to the history file, don't overwrite it
shopt -s extglob
shopt -s progcomp


if [[ -z "${_FENSALIR_UTF8_SUPPORT:-}" ]] \
       || [[ "${_FENSALIR_UTF8_SUPPORT,,}" == "y" ]] \
       || [[ "${_FENSALIR_UTF8_SUPPORT,,}" == "yes" ]]; then
    export LANG="en_US.UTF-8"
    export LANGUAGE="en_US.UTF-8"
    export LC_CTYPE="en_US.UTF-8"
    export LC_NUMERIC="en_US.UTF-8"
    export LC_TIME="en_US.UTF-8"
    export LC_COLLATE="C"
    export LC_MONETARY="en_US.UTF-8"
    export LC_MESSAGES="en_US.UTF-8"
    export LC_PAPER="C"
    export LC_NAME="en_US.UTF-8"
    export LC_ADDRESS="en_US.UTF-8"
    export LC_TELEPHONE="en_US.UTF-8"
    export LC_MEASUREMENT="C"
    export LC_IDENTIFICATION="C"

    # Get correct handling of UTF-8 in less (including Git log
    # messages, as it uses less)
    export LESSCHARSET=utf-8

    # Note: NEVER EVER define nor export the variable LC_ALL as it
    # acts as a global override for all other LC_*-settings above. The
    # 'C' locale is defined by POSIX and for some of the LC-variables
    # it is not allways desireble to use the same locale setting
    # across the board. For instance if LC_COLLATE is not set as "C"
    # then the ls command will sort filenames as if they were case
    # sensitive. And when listing all files including dot-files the
    # leading dot in the filenames is ignored.
fi

if [[ -z "${_FENSALIR_LESS_AS_PAGER:-}" ]] \
       || [[ "${_FENSALIR_LESS_AS_PAGER,,}" == "y" ]] \
       || [[ "${_FENSALIR_LESS_AS_PAGER,,}" == "yes" ]]; then
    # Get less instead of more for manual page pager; on Linux less is
    # the default pager
    export PAGER="less"

    # Color support in less
    if [[ -z "${_FENSALIR_LESS_COLOR:-}" ]] \
       || [[ "${_FENSALIR_LESS_COLOR,,}" == "y" ]] \
       || [[ "${_FENSALIR_LESS_COLOR,,}" == "yes" ]]; then
        export LESS="-R"
    fi
fi

if [[ -z "${_FENSALIR_LS_COLOR:-}" ]] \
       || [[ "${_FENSALIR_LS_COLOR,,}" == "y" ]] \
       || [[ "${_FENSALIR_LS_COLOR,,}" == "yes" ]]; then
    # Color support in less via an alias, unless an alias is already
    # defined
    if [[ "$(type -t ls)" == "file" ]]; then
        alias ls="ls --color=auto"
    fi
fi


case "${_FENSALIR_CURRENT_OS}" in
    ${_FENSALIR_LINUX})
        #echo "Linux system detected"
        if [[ -z "${_FENSALIR_COLOR_GNU_GREP:-}" ]] \
	       || [[ "${_FENSALIR_COLOR_GNU_GREP,,}" == "y" ]] \
	       || [[ "${_FENSALIR_COLOR_GNU_GREP,,}" == "yes" ]]
	then
            # Color support etc in GNU grep
            export GREP_OPTIONS="--color=auto --exclude-dir=.git"
        fi

        module --silent add bash-completion
	if [[ -v SAAB_BASH_COMPLETION ]]; then
	    if [[ -r "${SAAB_BASH_COMPLETION}/bash_completion" ]]; then
		source "${SAAB_BASH_COMPLETION}/bash_completion"
	    fi
	fi

        # Get environment variable set to point to PWA
        module --silent add pwa
        ;;
esac


# Find all files recursively who's name ends with '~', a sequence
# number like '.~1~', or is enclosed with '#' like '#fnord#'. The two
# former variants are backups created by emacs when saving a new
# version of a buffer and the latter is an Emacs auto-save file. Emacs
# lock files are explicitly not included (they start with '#' but have
# no matching '#' at the end like the auto-save files)
#
# Note that both SVN .svn folder and Git .git folder are explicitly
# excluded from the search. Note also that the Linux specific
# '-delete' action can not be used since it makes -prune to not work
# as it implies -depth.
function expunge()
{
    find "${1:-.}" \
         '(' -name ".git" -a -type d -prune ')' \
         -o '(' -name ".svn" -a -type d -prune ')' \
         -o '(' -name ".snapshot" -a -type d -prune ')' \
         -o '(' -type f \
         '(' -name "*~" -o -name "*.~?*~" -o -name "#*#" ')' \
         ')' \
         -print \
         -exec rm '{}' ';'
}


# Changes tab title in terminal to given value.
function settabtitle()
{
    echo -en "\033]0;${*}\a"
}
