################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################
#
# DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN WHEN FRIJA IS
# UPDATED OR (RE)INSTALLED
#
# Add line below to your personal .bashrc file
#
# source "${HOME}/_FENSALIR_USER_CONFIG_HOME_/scripts/userinit.bash"
#
################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################


# Bootstrap installation inserts name of configuration file in
# assignment below
_FENSALIR_CONFIG=_FENSALIRCONFIG_

# Bootstrap installation inserts name of configuration file containing
# non-changeable configuration (NCC) parameters in assignment below
_FENSALIR_NCC=_FENSALIRNCC_

# Path to folder containing this script
FENSALIR_USER_SCRIPT_HOME="${BASH_SOURCE[0]%/*}"

# Path to user-specific Fensalir configuration file
FENSALIR_USER_CONFIG_HOME="${FENSALIR_USER_SCRIPT_HOME%/*}"


# Path to where modules is (assumed) to be installed
MODULESHOME="${MODULESHOME:-/usr/share/modules}"

# Path to where modules needed by Fensalir are installed
_FENSALIR_MODULE_ROOT="/sw/modulefiles"

if [[ -d "${MODULESHOME}" ]]; then
    if [[ -r "${MODULESHOME}/init/bash" ]]; then
	# Initialize modules command for Bash
	source "${MODULESHOME}/init/bash"
    fi

    # If environment variable MODULE_PATH is defined, then it is
    # assumed that modules command exist and that it is meaningful to
    # append additional paths for searching for module files to it.
    if [[ -v MODULEPATH ]]; then
	if [[ -d "${_FENSALIR_MODULE_ROOT}" ]]; then
	    ! module use --append "${_FENSALIR_MODULE_ROOT}"
	fi
    fi
fi

if [[ -d "${FENSALIR_USER_CONFIG_HOME}" ]]; then
    if [[ -r "${FENSALIR_USER_CONFIG_HOME}/${_FENSALIR_NCC}" ]]
    then
        # shellcheck source=../.fensalirncc
        source "${FENSALIR_USER_CONFIG_HOME}/${_FENSALIR_NCC}"
    fi

    if [[ -r "${HOME}/${_FENSALIR_CONFIG}" ]]
    then
	echo "Sourcing '${HOME}/${_FENSALIR_CONFIG}'"
        # shellcheck source=../example.fensalirconfig
        source "${HOME}/${_FENSALIR_CONFIG}"
    elif [[ -r "${FENSALIR_USER_CONFIG_HOME}/${_FENSALIR_CONFIG}" ]]
    then
	echo "Sourcing '${FENSALIR_USER_CONFIG_HOME}/${_FENSALIR_CONFIG}'"
        # shellcheck source=../example.fensalirconfig
        source "${FENSALIR_USER_CONFIG_HOME}/${_FENSALIR_CONFIG}"
    fi

    FENSALIR_OS="${FENSALIR_USER_SCRIPT_HOME}/fensalir-identify-os.bash"
    if [[ -r "${FENSALIR_OS}" ]]; then
        # shellcheck source=./fensalir-identify-os.bash
        source "${FENSALIR_OS}"
    else
        cat <<EOF 1>&2

================================================================================
ERROR: Unable to identify current OS due to expected file
         '${FENSALIR_OS}
       is missing, aborting Fensalir environment initialization.

       Corrupt or non-existing Fensalir user configuration?
================================================================================

EOF
        unset FENSALIR_OS
        return
    fi
    unset FENSALIR_OS

    # On Solaris Bash 5 is used instead of Bash 3. Fensalir requires
    # Bash 4.2 or newer. This script will also configure Bash to
    # remove duplicate entries in its history (for instance what you
    # get when pressing up/down arrows), tells Bash to append to the
    # history file instead of overwriting it, turn on support for
    # extended globbing, and ensuring that programmable completion is
    # enabled (it is enabled by default).
    #
    # Note that a function called 'expunge' is also defined. This
    # function will recursively remove all Emacs backup and auto-save
    # files. If no argument is given the search starts in the current
    # directory. Optionally a path may be given as the first argument
    # and then the search starts in that directory.
    #
    # Also configures some aspects of Bash CLI
    # environment depending on configuration options above.
    if [[ -z "${_FENSALIR_BASH:-}" ]]; then
        FENSALIR_BASH="${FENSALIR_USER_SCRIPT_HOME}/fensalir-bash-setup.bash"
        if [[ -r "${FENSALIR_BASH}" ]]; then
            # shellcheck source=./fensalir-bash-setup.bash
            source "${FENSALIR_BASH}"
        fi
        unset FENSALIR_BASH
    fi

    # Activate latest installed version of Git. Fensalir may depend on
    # features available in latest version of Git. Also configures
    # some aspects of Git experience when using the CLI depending on
    # configuration options above.
    if [[ -z "${_FENSALIR_GIT:-}" ]]; then
        FENSALIR_GIT="${FENSALIR_USER_SCRIPT_HOME}/fensalir-git-setup.bash"
        if [[ -r "${FENSALIR_GIT}" ]]; then
            # shellcheck source=./fensalir-git-setup.bash
            source "${FENSALIR_GIT}"
        fi
        unset FENSALIR_GIT
    fi

    # Find out if Fensalir is installed, if so activate it. Configure
    # option _FENSALIR_FENSALIR in the personal Fensalir configuration
    # file sourced above to disable Fensalir initialization.
    if [[ -z "${_FENSALIR_FENSALIR:-}" ]]; then
        FENSALIR_ACTIVATE="${FENSALIR_USER_SCRIPT_HOME}/fensalir-activate.bash"
        if [[ -r "${FENSALIR_ACTIVATE}" ]]; then
            # shellcheck source=./fensalir-activate.bash
            source "${FENSALIR_ACTIVATE}"
        fi
        unset FENSALIR_ACTIVATE
    fi
fi
