################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################
#
# DO NOT EDIT THIS FILE AS IT WILL BE OVERWRITTEN WHEN FRIJA IS
# UPDATED OR (RE)INSTALLED
#
# Add line below to your personal .bashrc file
#
# source "${HOME}/_FENSALIR_USER_CONFIG_HOME_/scripts/userconfig.bash"
#
################################################################################
#  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  #
################################################################################


# Bootstrap installation inserts name of configuration file in
# assignment below
_FENSALIR_CONFIG=_FENSALIRCONFIG_

# Check what system we are running on. Fensalir support scripts and
# functions may depend on these variables being properly initialized.
_unameOut="$(uname -s)"

# Fensalir setup script and provided Bash support scripts depend on
# these variables being properly initialized and exported
export _FENSALIR_SOLARIS="Solaris"
export _FENSALIR_LINUX="Linux"
export _FENSALIR_WINDOWS="Windows"

case "${_unameOut}" in
    SunOS)
        _FENSALIR_CURRENT_OS="${_FENSALIR_SOLARIS}"
        ;;
    Linux*)
        _FENSALIR_CURRENT_OS="${_FENSALIR_LINUX}"
        ;;
    MINGW*)
        _FENSALIR_CURRENT_OS="${_FENSALIR_WINDOWS}"
        ;;
    *)
        echo "Unknown OS '${_unameOut}'" 1>&2
        return
        ;;
esac

export _FENSALIR_CURRENT_OS

FENSALIR_USER_CONFIG_HOME="${BASH_SOURCE[0]%/*}"
if [[ -d "${FENSALIR_USER_CONFIG_HOME}" ]]; then
    if [[ -r "${HOME}/${_FENSALIR_CONFIG}" ]]
    then
        # shellcheck source=../example.fensalirconfig
        source "${HOME}/${_FENSALIR_CONFIG}"
    elif [[ -r "${FENSALIR_USER_CONFIG_HOME}/${_FENSALIR_CONFIG}" ]]
    then
        # shellcheck source=../example.fensalirconfig
        source "${FENSALIR_USER_CONFIG_HOME}/${_FENSALIR_CONFIG}"
    fi

    # On Solaris Bash 5 is used instead of Bash 3. Fensalir requires
    # Bash 4.2 or newer. This script will also configure Bash to
    # remove duplicate entries in its history (for instance what you
    # get when pressing up/down arrows), tells Bash to append to the
    # history file instead of overwriting it, turn on support for
    # extended globbing, and ensuring that programmable completion is
    # enabled (it is enabled by default).
    #
    # Note that a function called 'expunge' is also defined. This
    # function will recursively remove all Emacs backup and auto-save
    # files. If no argument is given the search starts in the current
    # directory. Optionally a path may be given as the first argument
    # and then the search starts in that directory.
    #
    # Also configures some aspects of Bash CLI
    # environment depending on configuration options above.
    if [[ -z "${_FENSALIR_BASH:-}" ]]; then
        FENSALIR_BASH="${FENSALIR_USER_CONFIG_HOME}/fensalir-bash-setup.bash"
        if [[ -r "${FENSALIR_BASH}" ]]; then
            # shellcheck source=./fensalir-bash-setup.bash
            source "${FENSALIR_BASH}"
        fi
        unset FENSALIR_BASH
    fi

    # Activate latest installed version of Git. Fensalir may depend on
    # features available in latest version of Git. Also configures
    # some aspects of Git experience when using the CLI depending on
    # configuration options above.
    if [[ -z "${_FENSALIR_GIT:-}" ]]; then
        FENSALIR_GIT="${FENSALIR_USER_CONFIG_HOME}/fensalir-git-setup.bash"
        if [[ -r "${FENSALIR_GIT}" ]]; then
            # shellcheck source=./fensalir-git-setup.bash
            source "${FENSALIR_GIT}"
        fi
        unset FENSALIR_GIT
    fi

    # Find out if Fensalir is installed, if so activate it. Configure
    # option _FENSALIR_FENSALIR in the personal Fensalir configuration
    # file sourced above to disable Fensalir initialization.
    if [[ -z "${_FENSALIR_FENSALIR:-}" ]]; then
        FENSALIR_ACTIVATE="${FENSALIR_USER_CONFIG_HOME}/fensalir-activate.bash"
        if [[ -r "${FENSALIR_ACTIVATE}" ]]; then
            # shellcheck source=./fensalir-activate.bash
            source "${FENSALIR_ACTIVATE}"
        fi
        unset FENSALIR_ACTIVATE
    fi
fi
